{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"campeonato-brasileiro-cartoes\",\"campeonato-brasileiro-estatisticas-full\",\"campeonato-brasileiro-full\",\"campeonato-brasileiro-gols\",\"dim_clubes\",\"campeonato-brasileiro-full - mandantes\",\"campeonato-brasileiro-full - visitantes\",\"full - unpivot\",\"Tabela\",\"serie\",\"dim_jogadores\",\"dim_cores\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.137.952.0 (24.10)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "campeonato-brasileiro-full - mandantes",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = #\"campeonato-brasileiro-full\",",
          "    #\"Colunas Removidas\" = Table.RemoveColumns(Fonte,{\"visitante\", \"formacao_visitante\", \"tecnico_visitante\"}),",
          "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Colunas Removidas\",{{\"mandante_Placar\", \"gols_pro\"}, {\"visitante_Placar\", \"gols_contra\"}}),",
          "    #\"Colunas Removidas1\" = Table.RemoveColumns(#\"Colunas Renomeadas\",{\"mandante_Estado\", \"visitante_Estado\"}),",
          "    #\"Colunas Renomeadas1\" = Table.RenameColumns(#\"Colunas Removidas1\",{{\"formacao_mandante\", \"formacao\"}, {\"tecnico_mandante\", \"tecnico\"}}),",
          "    #\"Coluna Condicional Adicionada\" = Table.AddColumn(#\"Colunas Renomeadas1\", \"R\", each if [mandante] = [vencedor] then \"V\" else if [vencedor] = \"-\" then \"E\" else \"D\"),",
          "    #\"Personalização Adicionada\" = Table.AddColumn(#\"Coluna Condicional Adicionada\", \"mandante_flag\", each \"S\"),",
          "    #\"Colunas Renomeadas2\" = Table.RenameColumns(#\"Personalização Adicionada\",{{\"mandante\", \"time\"}})",
          "in",
          "    #\"Colunas Renomeadas2\""
        ],
        "kind": "m",
        "lineageTag": "ea77ef8f-45ed-44c4-86f0-78f539dca78f"
      },
      {
        "name": "campeonato-brasileiro-full - visitantes",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = #\"campeonato-brasileiro-full\",",
          "    #\"Colunas Removidas\" = Table.RemoveColumns(Fonte,{\"mandante\", \"formacao_mandante\", \"tecnico_mandante\"}),",
          "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Colunas Removidas\",{{\"visitante_Placar\", \"gols_pro\"}, {\"mandante_Placar\", \"gols_contra\"}}),",
          "    #\"Colunas Removidas1\" = Table.RemoveColumns(#\"Colunas Renomeadas\",{\"mandante_Estado\", \"visitante_Estado\"}),",
          "    #\"Colunas Renomeadas1\" = Table.RenameColumns(#\"Colunas Removidas1\",{{\"formacao_visitante\", \"formacao\"}, {\"tecnico_visitante\", \"tecnico\"}}),",
          "    #\"Coluna Condicional Adicionada\" = Table.AddColumn(#\"Colunas Renomeadas1\", \"R\", each if [visitante] = [vencedor] then \"V\" else if [vencedor] = \"-\" then \"E\" else \"D\"),",
          "    #\"Personalização Adicionada\" = Table.AddColumn(#\"Coluna Condicional Adicionada\", \"mandante_flag\", each \"N\"),",
          "    #\"Colunas Renomeadas2\" = Table.RenameColumns(#\"Personalização Adicionada\",{{\"visitante\", \"time\"}})",
          "in",
          "    #\"Colunas Renomeadas2\""
        ],
        "kind": "m",
        "lineageTag": "2b56c0c5-db0a-43a4-b528-544261a84c12"
      },
      {
        "name": "serie",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Excel.Workbook(File.Contents(\"C:\\Users\\MSI\\Documents\\PBI\\Brasileirao\\07-Brasileirao\\bases\\serie.xlsx\"), null, true),",
          "    Planilha1_Sheet = Fonte{[Item=\"Planilha1\",Kind=\"Sheet\"]}[Data],",
          "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Planilha1_Sheet,{{\"Column1\", type text}, {\"Column2\", type any}, {\"Column3\", type any}, {\"Column4\", type any}, {\"Column5\", type any}, {\"Column6\", type any}, {\"Column7\", type any}, {\"Column8\", type any}, {\"Column9\", type any}, {\"Column10\", type any}, {\"Column11\", type any}, {\"Column12\", type any}, {\"Column13\", type any}, {\"Column14\", type any}, {\"Column15\", type any}, {\"Column16\", type any}, {\"Column17\", type any}, {\"Column18\", type any}, {\"Column19\", type any}, {\"Column20\", type any}, {\"Column21\", type any}, {\"Column22\", type any}}),",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(#\"Tipo Alterado\", [PromoteAllScalars=true]),",
          "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"2003\", type text}, {\"2004\", type text}, {\"2005\", type text}, {\"2006\", type text}, {\"2007\", type text}, {\"2008\", type text}, {\"2009\", type text}, {\"2010\", type text}, {\"2011\", type text}, {\"2012\", type text}, {\"2013\", type text}, {\"2014\", type text}, {\"2015\", type text}, {\"2016\", type text}, {\"2017\", type text}, {\"2018\", type text}, {\"2019\", type text}, {\"2020\", type text}, {\"2021\", type text}, {\"2022\", type text}, {\"2023\", type text}}),",
          "    #\"Texto Aparado\" = Table.TransformColumns(#\"Tipo Alterado1\",{{\"Time\", Text.Trim, type text}}),",
          "    #\"Outras Colunas Não Dinâmicas\" = Table.UnpivotOtherColumns(#\"Texto Aparado\", {\"Time\"}, \"Atributo\", \"Valor\"),",
          "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Outras Colunas Não Dinâmicas\",{{\"Atributo\", \"Ano\"}, {\"Valor\", \"Serie\"}})",
          "in",
          "    #\"Colunas Renomeadas\""
        ],
        "kind": "m",
        "lineageTag": "9733a9aa-69ac-470e-a9db-59f0d3ab89ee"
      }
    ],
    "relationships": [
      {
        "name": "7485692f-a21c-ed78-46ac-ff7e067e30de",
        "fromColumn": "clube",
        "fromTable": "campeonato-brasileiro-cartoes",
        "isActive": false,
        "toColumn": "Clube_s_acentos",
        "toTable": "dim_clubes"
      },
      {
        "name": "4ce88cbb-9a99-57ec-5273-eee35e11f492",
        "fromColumn": "clube",
        "fromTable": "campeonato-brasileiro-estatisticas-full",
        "isActive": false,
        "toColumn": "Clube_s_acentos",
        "toTable": "dim_clubes"
      },
      {
        "name": "de53c435-1841-eb8a-133e-93bf5618fb42",
        "fromColumn": "mandante",
        "fromTable": "campeonato-brasileiro-full",
        "isActive": false,
        "toColumn": "Clube_s_acentos",
        "toTable": "dim_clubes"
      },
      {
        "name": "1c62e3f4-cacf-317d-5aaf-651a8bd8efff",
        "fromColumn": "visitante",
        "fromTable": "campeonato-brasileiro-full",
        "toColumn": "Clube_s_acentos",
        "toTable": "dim_clubes"
      },
      {
        "name": "e69b2d93-c2f9-378d-928e-e8e508c40545",
        "fromColumn": "clube",
        "fromTable": "campeonato-brasileiro-gols",
        "toColumn": "Clube_s_acentos",
        "toTable": "dim_clubes"
      },
      {
        "name": "b35b2f32-6cd9-bb2f-9626-2c745a5a829a",
        "fromColumn": "time",
        "fromTable": "full - unpivot",
        "toColumn": "Clube_s_acentos",
        "toTable": "dim_clubes"
      },
      {
        "name": "d4eaba62-9703-6eff-982f-01b8e3886a5b",
        "fromColumn": "Cores",
        "fromTable": "dim_clubes",
        "toColumn": "Coluna 1",
        "toTable": "Tabela"
      },
      {
        "name": "266e4fa8-1fc9-4be9-b247-e3d996aa4ef8",
        "fromColumn": "Fundacao",
        "fromTable": "dim_clubes",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_2ea599c2-7a12-48e5-845a-02093c9b8bcd"
      },
      {
        "name": "1d95649b-067b-260e-7b14-244f4b2c5bbb",
        "fromColumn": "atleta",
        "fromTable": "campeonato-brasileiro-gols",
        "toColumn": "atleta",
        "toTable": "dim_jogadores"
      },
      {
        "name": "4e45539d-8661-c63f-136c-6afea0ed92d2",
        "fromColumn": "atleta",
        "fromTable": "TabelaGolsPorClube",
        "toColumn": "atleta",
        "toTable": "dim_jogadores"
      },
      {
        "name": "ca954fa8-28d3-e1eb-1f4f-1edc64c72c0d",
        "fromColumn": "clube",
        "fromTable": "TabelaGolsPorClube",
        "toColumn": "Clube_s_acentos",
        "toTable": "dim_clubes"
      },
      {
        "name": "b6dc83ee-06a7-cb97-42c8-9b3cdcfa3166",
        "fromColumn": "atleta",
        "fromTable": "campeonato-brasileiro-cartoes",
        "toColumn": "atleta",
        "toTable": "dim_jogadores"
      },
      {
        "name": "dec125e1-28b3-cb8e-1958-2a0a4262f28f",
        "fromColumn": "data",
        "fromTable": "campeonato-brasileiro-full",
        "toColumn": "Date",
        "toTable": "dCalendar"
      },
      {
        "name": "af234060-970c-3270-4b43-b008a5e71424",
        "fromColumn": "Dt Nascimento",
        "fromTable": "dim_jogadores",
        "toColumn": "Date",
        "toTable": "dCalendar"
      },
      {
        "name": "95648a65-ec66-f428-bf13-9ccd3ebb0986",
        "fromColumn": "data",
        "fromTable": "full - unpivot",
        "toColumn": "Date",
        "toTable": "dCalendar"
      },
      {
        "name": "1552c350-e6b7-c066-cbec-7463cc615f0a",
        "fromColumn": "Ano-Campeonato",
        "fromTable": "dCalendar",
        "toColumn": "Ano",
        "toTable": "dAno"
      },
      {
        "name": "e7b94801-9900-a912-557b-62e867d9d1d6",
        "fromColumn": "time",
        "fromTable": "fct_classificacao",
        "toColumn": "Clube_s_acentos",
        "toTable": "dim_clubes"
      },
      {
        "name": "3a340562-2cd7-bdfa-150c-ee498a4603df",
        "fromColumn": "Ano",
        "fromTable": "fct_classificacao",
        "toColumn": "Ano",
        "toTable": "dAno"
      },
      {
        "name": "e72fa365-0992-b9bf-770b-a0b417c4b329",
        "fromColumn": "Cores",
        "fromTable": "dim_clubes",
        "toColumn": "Cor",
        "toTable": "dim_cores"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "campeonato-brasileiro-cartoes",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "partida_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "51ac3b8e-202c-4793-b28c-debf99b6f03a",
            "sourceColumn": "partida_id",
            "summarizeBy": "sum"
          },
          {
            "name": "rodata",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "70d52035-2994-488e-91b8-b00cd86a67f7",
            "sourceColumn": "rodata",
            "summarizeBy": "sum"
          },
          {
            "name": "clube",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0562273c-c1f2-4a32-9ce5-fb414705a8ca",
            "sourceColumn": "clube",
            "summarizeBy": "none"
          },
          {
            "name": "cartao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "acecaff9-b1a4-4d47-86c1-52e2628e6e06",
            "sourceColumn": "cartao",
            "summarizeBy": "none"
          },
          {
            "name": "atleta",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6cf16c92-e7fd-494c-ad62-e1ca6f8ac21f",
            "sourceColumn": "atleta",
            "summarizeBy": "none"
          },
          {
            "name": "num_camisa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a0840383-fc53-41f2-b2a5-648e4faa15ff",
            "sourceColumn": "num_camisa",
            "summarizeBy": "sum"
          },
          {
            "name": "posicao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "93d352a3-6b87-42f5-8897-cdc04ec8cdc6",
            "sourceColumn": "posicao",
            "summarizeBy": "none"
          },
          {
            "name": "minuto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f76660b8-6feb-4d8f-a3c3-96ab152364b2",
            "sourceColumn": "minuto",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "38b31757-60fd-41af-8ae7-4f9a0b290e9c",
        "measures": [
          {
            "name": "_timeselecionado",
            "expression": [
              "IF(",
              "    ISBLANK(SELECTEDVALUE(dim_clubes[Clube])),",
              "    \"Brasileirão\",",
              "    UPPER(MIN(dim_clubes[Clube]))",
              ")"
            ],
            "lineageTag": "791b3ce7-966e-4eef-8d75-d810279fce2e"
          },
          {
            "name": "_playhino",
            "expression": [
              "",
              "VAR clube = SELECTEDVALUE(dim_clubes[Clube_s_acentos])",
              "VAR clubeFormatado = SUBSTITUTE(clube, \" \", \"-\")",
              "",
              "RETURN ",
              "IF(",
              "    NOT ISBLANK(clube),",
              "    \"<audio controls autoplay",
              "        src='https://github.com/anapaccasilva/CampeonatoBrasileiro/raw/refs/heads/main/Hinos/hino-\" & clubeFormatado & \".mp3' ",
              "        type='audio/mp3'",
              "        style='width: 100%; height: 80px; transform: scale(1);'>",
              "    </audio>\",",
              "    \"\"",
              ")",
              ""
            ],
            "lineageTag": "94176c8e-8c94-48d9-81bb-087f7da2dcbd"
          },
          {
            "name": "_escudo",
            "dataCategory": "ImageUrl",
            "expression": [
              "",
              "VAR clube = SELECTEDVALUE(dim_clubes[Clube_s_acentos])",
              "",
              "RETURN ",
              "IF(",
              "    NOT ISBLANK(clube),",
              "    MAX(dim_clubes[Url]),",
              "    \"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1uSPqhbyjTCOXnknUKaEbXKEFeFFakCl0zwVEHp9dfwDS8un4vi9Xal0ey5qO4epyv_E&usqp=CAU\"",
              ")",
              ""
            ],
            "lineageTag": "d434d11d-62ad-4513-9073-a491d5c03ec8"
          }
        ],
        "partitions": [
          {
            "name": "campeonato-brasileiro-cartoes",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\MSI\\Documents\\PBI\\Brasileirao\\07-Brasileirao\\campeonato-brasileiro-cartoes.csv\"),[Delimiter=\",\", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"partida_id\", Int64.Type}, {\"rodata\", Int64.Type}, {\"clube\", type text}, {\"cartao\", type text}, {\"atleta\", type text}, {\"num_camisa\", Int64.Type}, {\"posicao\", type text}, {\"minuto\", type text}}),",
                "    #\"Valor Substituído\" = Table.ReplaceValue(#\"Tipo Alterado\",\"Clayson\",\"Clayson Henrique da Silva Vieira\",Replacer.ReplaceValue,{\"atleta\"}),",
                "    #\"Valor Substituído1\" = Table.ReplaceValue(#\"Valor Substituído\",\"\",\"Everton Kempes dos Santos\",Replacer.ReplaceValue,{\"atleta\"}),",
                "    #\"Valor Substituído2\" = Table.ReplaceValue(#\"Valor Substituído1\",\"Gabriel Barbosa Almeida\",\"Gabriel Barbosa\",Replacer.ReplaceText,{\"atleta\"})",
                "in",
                "    #\"Valor Substituído2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "campeonato-brasileiro-estatisticas-full",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "partida_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "64866a08-9ca2-4bb9-9cfa-8d3334b46e91",
            "sourceColumn": "partida_id",
            "summarizeBy": "sum"
          },
          {
            "name": "rodata",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c2b3657e-d4f5-4eb1-a8fb-cbe7090a80fb",
            "sourceColumn": "rodata",
            "summarizeBy": "sum"
          },
          {
            "name": "clube",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "37c37d2c-7353-45e1-a5bb-d42ccb11a056",
            "sourceColumn": "clube",
            "summarizeBy": "none"
          },
          {
            "name": "chutes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fd0f1b3e-41c2-4bcd-a5bb-927c2a8543fa",
            "sourceColumn": "chutes",
            "summarizeBy": "sum"
          },
          {
            "name": "chutes_no_alvo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7658e934-8706-4b41-918d-89ee3cec2d45",
            "sourceColumn": "chutes_no_alvo",
            "summarizeBy": "sum"
          },
          {
            "name": "posse_de_bola",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1b4f5f9d-2975-4783-afc5-cc44c37b5db2",
            "sourceColumn": "posse_de_bola",
            "summarizeBy": "none"
          },
          {
            "name": "passes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a1a61e68-d33e-4d18-b5a2-7e29a26ff150",
            "sourceColumn": "passes",
            "summarizeBy": "sum"
          },
          {
            "name": "precisao_passes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0de7ace3-083d-4b18-8447-359aa203d72b",
            "sourceColumn": "precisao_passes",
            "summarizeBy": "none"
          },
          {
            "name": "faltas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d0684aac-3272-43a4-8b4b-72c387f23a97",
            "sourceColumn": "faltas",
            "summarizeBy": "sum"
          },
          {
            "name": "cartao_amarelo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "159595d8-25e9-4895-91c8-6fc23b6be9b8",
            "sourceColumn": "cartao_amarelo",
            "summarizeBy": "sum"
          },
          {
            "name": "cartao_vermelho",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "70d26830-4172-45df-82cc-24b4bd147b14",
            "sourceColumn": "cartao_vermelho",
            "summarizeBy": "sum"
          },
          {
            "name": "impedimentos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "29444abc-c977-42b5-a0fa-ee3535bb5965",
            "sourceColumn": "impedimentos",
            "summarizeBy": "sum"
          },
          {
            "name": "escanteios",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0714fe4e-3980-425c-af56-f4fd6791480c",
            "sourceColumn": "escanteios",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "8d6dccab-488c-4245-9950-6a8d8ce1d50e",
        "partitions": [
          {
            "name": "campeonato-brasileiro-estatisticas-full",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\MSI\\Documents\\PBI\\Brasileirao\\07-Brasileirao\\campeonato-brasileiro-estatisticas-full.csv\"),[Delimiter=\",\", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"partida_id\", Int64.Type}, {\"rodata\", Int64.Type}, {\"clube\", type text}, {\"chutes\", Int64.Type}, {\"chutes_no_alvo\", Int64.Type}, {\"posse_de_bola\", type text}, {\"passes\", Int64.Type}, {\"precisao_passes\", type text}, {\"faltas\", Int64.Type}, {\"cartao_amarelo\", Int64.Type}, {\"cartao_vermelho\", Int64.Type}, {\"impedimentos\", Int64.Type}, {\"escanteios\", Int64.Type}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "campeonato-brasileiro-full",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "954838e0-e208-46e6-a9ca-9ed269a6cb73",
            "sourceColumn": "ID",
            "summarizeBy": "count"
          },
          {
            "name": "rodata",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fbd6b11c-0c42-4b1c-b922-f490fb35da0c",
            "sourceColumn": "rodata",
            "summarizeBy": "sum"
          },
          {
            "name": "data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "c5cd787e-479a-4b97-8f2e-2d5bdfb55c01",
            "sourceColumn": "data",
            "summarizeBy": "none"
          },
          {
            "name": "hora",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "9bfa20c2-31ad-4eee-a3b9-198b6902c279",
            "sourceColumn": "hora",
            "summarizeBy": "none"
          },
          {
            "name": "mandante",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "18484272-1f9c-42a9-99a1-63e7b9798ec0",
            "sourceColumn": "mandante",
            "summarizeBy": "none"
          },
          {
            "name": "visitante",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e9b479b9-201d-4a28-b49a-0789543702df",
            "sourceColumn": "visitante",
            "summarizeBy": "none"
          },
          {
            "name": "formacao_mandante",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a3b2f7da-36cd-410e-8511-198fee22db5a",
            "sourceColumn": "formacao_mandante",
            "summarizeBy": "none"
          },
          {
            "name": "formacao_visitante",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "903b5b67-9d2f-4913-87e2-1d4b818cef75",
            "sourceColumn": "formacao_visitante",
            "summarizeBy": "none"
          },
          {
            "name": "tecnico_mandante",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "50d83ecc-d592-4673-ab73-9eb28f299f8a",
            "sourceColumn": "tecnico_mandante",
            "summarizeBy": "none"
          },
          {
            "name": "tecnico_visitante",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a8b4edcb-d7a3-497b-a7c4-e3d2c700aeb2",
            "sourceColumn": "tecnico_visitante",
            "summarizeBy": "none"
          },
          {
            "name": "vencedor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f730fda2-0e45-4178-b664-429d07b641bd",
            "sourceColumn": "vencedor",
            "summarizeBy": "none"
          },
          {
            "name": "arena",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "22063f8c-42a3-4508-aed8-1e776a51f8e4",
            "sourceColumn": "arena",
            "summarizeBy": "none"
          },
          {
            "name": "mandante_Placar",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "951c8ac2-4a02-4a33-8299-4f1d9bb2123f",
            "sourceColumn": "mandante_Placar",
            "summarizeBy": "sum"
          },
          {
            "name": "visitante_Placar",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c50aaf25-b3af-4707-a010-8120686b8b3b",
            "sourceColumn": "visitante_Placar",
            "summarizeBy": "sum"
          },
          {
            "name": "mandante_Estado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e09913fe-dd6b-4868-9f04-aa438745831b",
            "sourceColumn": "mandante_Estado",
            "summarizeBy": "none"
          },
          {
            "name": "visitante_Estado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ca8113c2-16dd-41fd-9e29-9e490fcb20da",
            "sourceColumn": "visitante_Estado",
            "summarizeBy": "none"
          },
          {
            "name": "Série",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ecf2d136-e437-4f80-a15c-eb2c02006ab5",
            "sourceColumn": "Série",
            "summarizeBy": "none"
          },
          {
            "name": "Índice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "RANKX(ALL('campeonato-brasileiro-full'[data]), 'campeonato-brasileiro-full'[data], , DESC)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "663a5d3e-498e-41ae-b71d-175f990e5f72",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "48de3af7-b806-4f41-90f2-52046510aa32",
        "partitions": [
          {
            "name": "campeonato-brasileiro-full",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\MSI\\Documents\\PBI\\Brasileirao\\07-Brasileirao\\campeonato-brasileiro-full.csv\"),[Delimiter=\",\", Columns=16, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"ID\", Int64.Type}, {\"rodata\", Int64.Type}, {\"data\", type date}, {\"hora\", type time}, {\"mandante\", type text}, {\"visitante\", type text}, {\"formacao_mandante\", type text}, {\"formacao_visitante\", type text}, {\"tecnico_mandante\", type text}, {\"tecnico_visitante\", type text}, {\"vencedor\", type text}, {\"arena\", type text}, {\"mandante_Placar\", Int64.Type}, {\"visitante_Placar\", Int64.Type}, {\"mandante_Estado\", type text}, {\"visitante_Estado\", type text}}),",
                "    #\"Coluna Duplicada\" = Table.DuplicateColumn(#\"Tipo Alterado\", \"data\", \"Ano\"),",
                "    #\"Ano Extraído\" = Table.TransformColumns(#\"Coluna Duplicada\",{{\"Ano\", Date.Year, Int64.Type}}),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Ano Extraído\",{{\"Ano\", type text}}),",
                "    #\"Consultas Mescladas\" = Table.NestedJoin(#\"Tipo Alterado1\", {\"mandante\", \"Ano\"}, serie, {\"Time\", \"Ano\"}, \"serie\", JoinKind.LeftOuter),",
                "    #\"serie Expandido\" = Table.ExpandTableColumn(#\"Consultas Mescladas\", \"serie\", {\"Serie\"}, {\"Serie Mandante\"}),",
                "    Personalizar1 = Table.NestedJoin(#\"serie Expandido\", {\"visitante\", \"Ano\"}, serie, {\"Time\", \"Ano\"}, \"serie\", JoinKind.LeftOuter),",
                "    #\"serie Expandido1\" = Table.ExpandTableColumn(Personalizar1, \"serie\", {\"Serie\"}, {\"Serie Visitante\"}),",
                "    // Devido a pandemia de Covid a temporada de 2020 terminou em janeiro de 2021, de modo que em um mesmo ano alguns clubes jogaram em mais de uma divisão, porém em temporadas diferentes",
                "    #\"Coluna Condicional Adicionada\" = Table.AddColumn(#\"serie Expandido1\", \"Série\", each if [Serie Mandante] = [Serie Visitante] then [Serie Mandante] else \"A\"),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Coluna Condicional Adicionada\",{\"Ano\", \"Serie Mandante\", \"Serie Visitante\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_009a5668-6064-4e0d-bf66-b0c62ba2080c",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "415c0e4c-09e2-4444-b10c-224a39b919fa",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "75e0bd37-2668-4f22-8e58-5e8c2f64148e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "efbd0066-9e36-4997-b3bc-edd360e091f0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "ee7461da-894b-40d6-827e-a61991be7501",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "14115425-7e2f-4ad7-adf8-4e2579aa8854",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "5c5fa66d-b2d7-4633-94c2-c0ce6bae78ac",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "746fd682-2663-411c-9922-223784ffee47",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "d62f6abb-7577-4056-81c6-964647642f4d",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "7771544d-1211-41b4-ab6d-29d45ce2e504",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "bae407a4-588a-4d07-a26a-00643d68e78a",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "2a8d1386-a1e0-4d15-bea3-4bb94eb11d7f",
                "ordinal": 3
              }
            ],
            "lineageTag": "cc320c29-80e5-4972-8304-9e7062a1513f"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "01789f1f-5b2d-4da4-97f3-d1c5c0d0eac8",
        "partitions": [
          {
            "name": "DateTableTemplate_009a5668-6064-4e0d-bf66-b0c62ba2080c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "campeonato-brasileiro-gols",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "partida_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cd9d884b-3499-467f-b31c-2eb4a8af14ee",
            "sourceColumn": "partida_id",
            "summarizeBy": "sum"
          },
          {
            "name": "rodata",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4196f343-b53e-4fab-ac86-7e1955c601af",
            "sourceColumn": "rodata",
            "summarizeBy": "sum"
          },
          {
            "name": "clube",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70ae1092-7790-470e-97a6-71171f1cb29b",
            "sourceColumn": "clube",
            "summarizeBy": "none"
          },
          {
            "name": "atleta",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b9b44213-2fe1-4802-bfa4-67a335e64866",
            "sourceColumn": "atleta",
            "summarizeBy": "none"
          },
          {
            "name": "minuto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5272bed5-50e5-4418-ad9e-97e9467a63a6",
            "sourceColumn": "minuto",
            "summarizeBy": "sum"
          },
          {
            "name": "tipo_de_gol",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5828078e-c212-49bf-9445-a216a737b0df",
            "sourceColumn": "tipo_de_gol",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "83731422-4df4-47e4-894f-8788026dff4d",
        "partitions": [
          {
            "name": "campeonato-brasileiro-gols",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\MSI\\Documents\\PBI\\Brasileirao\\07-Brasileirao\\campeonato-brasileiro-gols.csv\"),[Delimiter=\",\", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"partida_id\", Int64.Type}, {\"rodata\", Int64.Type}, {\"clube\", type text}, {\"atleta\", type text}, {\"minuto\", type text}, {\"tipo_de_gol\", type text}}),",
                "    #\"Valor Substituído\" = Table.ReplaceValue(#\"Tipo Alterado\",\"Everton Kempes dos Santos Gonçalves\",\"Everton Kempes dos Santos\",Replacer.ReplaceText,{\"atleta\"}),",
                "    #\"Valor Substituído1\" = Table.ReplaceValue(#\"Valor Substituído\",\"Gabriel Barbosa Almeida\",\"Gabriel Barbosa\",Replacer.ReplaceText,{\"atleta\"}),",
                "    #\"Dividir Coluna por Delimitador\" = Table.SplitColumn(#\"Valor Substituído1\", \"minuto\", Splitter.SplitTextByDelimiter(\"+\", QuoteStyle.Csv), {\"minuto.1\", \"minuto.2\"}),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Dividir Coluna por Delimitador\",{{\"minuto.1\", Int64.Type}, {\"minuto.2\", Int64.Type}}),",
                "    #\"Valor Substituído2\" = Table.ReplaceValue(#\"Tipo Alterado1\",null,0,Replacer.ReplaceValue,{\"minuto.2\"}),",
                "    #\"Personalização Adicionada\" = Table.AddColumn(#\"Valor Substituído2\", \"minuto\", each [minuto.1]+[minuto.2]),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Personalização Adicionada\",{\"minuto.2\", \"minuto.1\"}),",
                "    #\"Tipo Alterado2\" = Table.TransformColumnTypes(#\"Colunas Removidas\",{{\"minuto\", Int64.Type}})",
                "in",
                "    #\"Tipo Alterado2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_clubes",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Clube",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c67efa65-75cf-4bfe-948b-acbb385dd18d",
            "sourceColumn": "Clube",
            "summarizeBy": "none"
          },
          {
            "name": "Fundacao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "a64cc4e3-d015-4b94-9723-ec3cd835b0b3",
            "sourceColumn": "Fundacao",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_2ea599c2-7a12-48e5-845a-02093c9b8bcd"
                },
                "isDefault": true,
                "relationship": "266e4fa8-1fc9-4be9-b247-e3d996aa4ef8"
              }
            ]
          },
          {
            "name": "Mascote",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "80299c1b-f7b9-44b0-997b-07b5e912c466",
            "sourceColumn": "Mascote",
            "summarizeBy": "none"
          },
          {
            "name": "Estadio",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f0780a50-d2d2-4a15-9b9f-8d720e02d151",
            "sourceColumn": "Estadio",
            "summarizeBy": "none"
          },
          {
            "name": "Cores",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "465f7a19-c847-415e-9c4e-828380ce5d65",
            "sourceColumn": "Cores",
            "summarizeBy": "none"
          },
          {
            "name": "Apelido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "df41b987-f85d-4253-a80e-289e34545b5d",
            "sourceColumn": "Apelido",
            "summarizeBy": "none"
          },
          {
            "name": "Clube_s_acentos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c90f949c-d573-4d03-8112-8c39f2d69e89",
            "sourceColumn": "Clube_s_acentos",
            "summarizeBy": "none"
          },
          {
            "name": "Url",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "a0bc7821-4615-4658-9b71-228fb4e3c14d",
            "sortByColumn": "id",
            "sourceColumn": "Url",
            "summarizeBy": "none"
          },
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "49b7da18-fcbe-418e-864a-e7a932dc00a0",
            "sourceColumn": "id",
            "summarizeBy": "sum"
          },
          {
            "name": "bg",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "expression": "RELATED(Tabela[Coluna 2])",
            "isDataTypeInferred": true,
            "lineageTag": "d531195d-512e-4fc5-a352-78722c398019",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Cidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "City",
            "dataType": "string",
            "lineageTag": "5b70cc9e-75b8-432c-9910-183004e026ed",
            "sourceColumn": "Cidade",
            "summarizeBy": "none"
          },
          {
            "name": "Estado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "StateOrProvince",
            "dataType": "string",
            "lineageTag": "33052850-d2fb-4c9b-ade4-4f8ada12b24c",
            "sourceColumn": "Estado",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "56adcef3-ffc6-4210-ba8e-c9f949acac9c",
        "partitions": [
          {
            "name": "dim_clubes",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Excel.Workbook(File.Contents(\"C:\\Users\\MSI\\Documents\\PBI\\Brasileirao\\07-Brasileirao\\clubes.xlsx\"), null, true),",
                "    Planilha2_Sheet = Fonte{[Item=\"Planilha2\",Kind=\"Sheet\"]}[Data],",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Planilha2_Sheet, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"Clube\", type text}, {\"Fundacao\", type date}, {\"Mascote\", type text}, {\"Estadio\", type text}, {\"Cores\", type text}, {\"Apelido\", type text}, {\"id\", Int64.Type}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "full - unpivot",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cf5dbd8c-0a70-4285-835e-6be244e8ea11",
            "sourceColumn": "ID",
            "summarizeBy": "count"
          },
          {
            "name": "rodata",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "72d09a71-e285-4f24-aaba-c43e059e2e1d",
            "sourceColumn": "rodata",
            "summarizeBy": "sum"
          },
          {
            "name": "data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "894ef71e-38c2-468c-9996-bbb5ac7a72b0",
            "sourceColumn": "data",
            "summarizeBy": "none"
          },
          {
            "name": "hora",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "576e1f24-5c18-40fb-ae88-3acd5e8b321b",
            "sourceColumn": "hora",
            "summarizeBy": "none"
          },
          {
            "name": "time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1a566142-801d-41b2-8dee-73a96e0e3fe1",
            "sourceColumn": "time",
            "summarizeBy": "none"
          },
          {
            "name": "formacao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dce43fa3-7568-45eb-b32b-1cb791392a1a",
            "sourceColumn": "formacao",
            "summarizeBy": "none"
          },
          {
            "name": "tecnico",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "05284de8-5658-4a1d-be57-3b95f337e031",
            "sourceColumn": "tecnico",
            "summarizeBy": "none"
          },
          {
            "name": "vencedor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "386e8b4c-e764-4f92-a067-5c6797656c06",
            "sourceColumn": "vencedor",
            "summarizeBy": "none"
          },
          {
            "name": "arena",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "91b67f38-369c-4a5e-8d90-4257724ca75a",
            "sourceColumn": "arena",
            "summarizeBy": "none"
          },
          {
            "name": "gols_contra",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dc9a9eef-ad47-464d-b371-e80f9a60399b",
            "sourceColumn": "gols_contra",
            "summarizeBy": "sum"
          },
          {
            "name": "gols_pro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "238d6d9e-cd94-4f4e-862e-21384565fe7c",
            "sourceColumn": "gols_pro",
            "summarizeBy": "sum"
          },
          {
            "name": "mandante_flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a247ab7e-a83a-437f-8b26-29023274918a",
            "sourceColumn": "mandante_flag",
            "summarizeBy": "none"
          },
          {
            "name": "R",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "520c3056-7d1a-46ae-b752-a8de3d17a9ff",
            "sourceColumn": "R",
            "summarizeBy": "none"
          },
          {
            "name": "Pontos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "786d8ccd-6b26-4ae9-9cc4-cdf5cd2b83cf",
            "sourceColumn": "Pontos",
            "summarizeBy": "sum"
          },
          {
            "name": "Saldo Gols",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "182e1428-0d4b-420e-a2fb-c9c10c81421e",
            "sourceColumn": "Saldo Gols",
            "summarizeBy": "sum"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "YEAR('full - unpivot'[data])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "51c127ad-ef29-45be-ba45-d4b5932e0ed1",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Série",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "214d680a-65d7-4c44-b6c0-5f75a35b4554",
            "sourceColumn": "Série",
            "summarizeBy": "none"
          },
          {
            "name": "Ranking por Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "436ba87b-9c83-4389-a31b-ebd06a36be98",
                "value": "{\"Expression\":\"\\nVAR anoLinha = YEAR('full - unpivot'[data])\\nVAR clubeLinha = 'full - unpivot'[time]\\n\\nRETURN\\nRANKX(\\n    FILTER(\\n        'full - unpivot',\\n        YEAR('full - unpivot'[data]) = anoLinha\\n    ),\\n    CALCULATE(SUM('full - unpivot'[Pontos])),\\n    ,\\n    DESC,\\n    DENSE\\n)\\n\"}"
              },
              {
                "name": "277cc1b9-af89-4597-8e15-cacc25c0886b",
                "value": [
                  "Uma dependência circular foi detectada: full - unpivot[Ranking por Ano].",
                  ""
                ]
              }
            ],
            "dataType": "int64",
            "isDataTypeInferred": true,
            "lineageTag": "3444a759-2348-4606-9696-b8e17ae18056",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "7e701944-8194-40b8-b1c8-86c00e76efa4",
        "partitions": [
          {
            "name": "full - unpivot",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.Combine({#\"campeonato-brasileiro-full - visitantes\", #\"campeonato-brasileiro-full - mandantes\"}),",
                "    #\"Coluna Condicional Adicionada\" = Table.AddColumn(Fonte, \"Pontos\", each if [R] = \"V\" then 3 else if [R] = \"E\" then 1 else 0),",
                "    #\"Subtração Inserida\" = Table.AddColumn(#\"Coluna Condicional Adicionada\", \"Saldo Gols\", each [gols_pro] - [gols_contra], type number),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Subtração Inserida\",{{\"Pontos\", Int64.Type}}),",
                "    #\"Texto Aparado\" = Table.TransformColumns(#\"Tipo Alterado\",{{\"arena\", Text.Trim, type text}})",
                "in",
                "    #\"Texto Aparado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Tabela",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "Coluna 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c9d28283-5cd8-4483-aefc-b1259e1e8e31",
            "sourceColumn": "Coluna 1",
            "summarizeBy": "none"
          },
          {
            "name": "Coluna 2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "ea24d214-ac10-4d1b-a366-be24c470a53a",
            "sourceColumn": "Coluna 2",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "68364dc8-d8c8-497e-ae8d-c800d7471d72",
        "measures": [
          {
            "name": "_jogos",
            "expression": "DISTINCTCOUNT('full - unpivot'[ID])",
            "formatString": "0",
            "lineageTag": "ef39c0b8-2ddf-4084-ad5f-4cdde504fefb"
          },
          {
            "name": "_vitorias",
            "expression": "CALCULATE(DISTINCTCOUNT('full - unpivot'[ID]), 'full - unpivot'[R] = \"V\")",
            "formatString": "0",
            "lineageTag": "c5c9cca4-4712-4426-9e9b-a5305db414f8"
          },
          {
            "name": "_empates",
            "expression": "CALCULATE(DISTINCTCOUNT('full - unpivot'[ID]), 'full - unpivot'[R] = \"E\")",
            "formatString": "0",
            "lineageTag": "91aa50ee-4f5d-426c-af11-3cc02508ef68"
          },
          {
            "name": "_derrotas",
            "expression": "CALCULATE(DISTINCTCOUNT('full - unpivot'[ID]), 'full - unpivot'[R] = \"D\")",
            "formatString": "0",
            "lineageTag": "704bed9e-f1de-475e-aadf-2a0188c8cfe0"
          },
          {
            "name": "_pontos",
            "expression": "sum('full - unpivot'[Pontos])",
            "formatString": "0",
            "lineageTag": "a8c9881b-4221-4de9-a706-a1cc97fa9549"
          },
          {
            "name": "_GP",
            "expression": "sum('full - unpivot'[gols_pro])",
            "formatString": "0",
            "lineageTag": "32d8e462-5c2d-4d4b-accd-05dc044eb71f"
          },
          {
            "name": "_GC",
            "expression": "sum('full - unpivot'[gols_contra])",
            "formatString": "0",
            "lineageTag": "4582459a-cc1a-4837-a4bb-df52793fd7c9"
          },
          {
            "name": "_SG",
            "expression": "sum('full - unpivot'[Saldo Gols])",
            "formatString": "0",
            "lineageTag": "54d6d332-45a9-48ba-9d00-979a67010d6d"
          },
          {
            "name": "_ranking",
            "expression": [
              "",
              "VAR AnoLinha = MAX('full - unpivot'[Ano]) -- supondo que você tenha uma coluna [Ano]",
              "VAR TabelaRanking =",
              "    ADDCOLUMNS(",
              "        FILTER(",
              "            fct_classificacao,",
              "            fct_classificacao[Ano] = AnoLinha",
              "        ),",
              "        \"ScoreDesempate\", ",
              "            fct_classificacao[TotalPontos] * 1000000 +",
              "            fct_classificacao[TotalVitorias] * 10000 +",
              "            fct_classificacao[SaldoGols] * 100 +",
              "            fct_classificacao[GolsPro]",
              "    )",
              "",
              "VAR TimeSelecionado =",
              "    MAX(fct_classificacao[Time]) -- Substitua pelo nome real da coluna de time",
              "",
              "VAR ScoreSelecionado =",
              "    CALCULATE(",
              "        MAXX(",
              "            FILTER(TabelaRanking, fct_classificacao[Time] = TimeSelecionado),",
              "            fct_classificacao[TotalPontos] * 1000000 +",
              "            fct_classificacao[TotalVitorias] * 10000 +",
              "            fct_classificacao[SaldoGols] * 100 +",
              "            fct_classificacao[GolsPro]",
              "        )",
              "    )",
              "",
              "RETURN",
              "RANKX(",
              "    TabelaRanking,",
              "    [ScoreDesempate],",
              "    ScoreSelecionado,",
              "    DESC,",
              "    DENSE",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "8bd74a70-2db1-4a31-8022-4db8725a4043"
          },
          {
            "name": "Cards",
            "expression": [
              "",
              "VAR _Imagem = MIN(dim_jogadores[Imagem])",
              "VAR _Posicao = MIN(dim_jogadores[Posição])",
              "VAR _JogadorNome = min(dim_jogadores[atleta])",
              "VAR _Nascimento = min(dim_jogadores[Dt Nascimento])",
              "VAR _Nacionalidade = min(dim_jogadores[Nacionalidade]) ",
              "VAR _GolsTemporada = CALCULATE(count('campeonato-brasileiro-gols'[partida_id]), dim_jogadores[atleta] = _JogadorNome)",
              "",
              "Return",
              "",
              "\"<!DOCTYPE html>",
              "<html lang='en'>",
              "<head>",
              "    <meta charset='UTF-8'>",
              "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>",
              "    <title>Compact Gallery Card</title>",
              "    <style>",
              "        body {",
              "            margin: 0;",
              "            padding: 8px;",
              "            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;",
              "        }",
              "        .card {",
              "            width: 147px;",
              "            margin: 12px auto;",
              "            border-radius: 10px;",
              "            overflow: hidden;",
              "            box-shadow: 0 2px 6px rgba(0, 0, 0, 0.1);",
              "            transition: transform 0.3s ease, box-shadow 0.3s ease;",
              "            background-color: #ffffff;",
              "        }",
              "        .card:hover {",
              "            transform: translateY(-6px);",
              "            box-shadow: 0 4px 14px rgba(0, 0, 0, 0.15);",
              "        }",
              "        .card-image-container {",
              "            position: relative;",
              "            height: 192px;",
              "            overflow: hidden;",
              "        }",
              "        .card-image {",
              "            width: 100%;",
              "            height: 100%;",
              "            object-fit: cover;",
              "            transition: transform 0.3s ease;",
              "        }",
              "        .card:hover .card-image {",
              "            transform: scale(1.05);",
              "        }",
              "        .card-content {",
              "            padding: 10px;",
              "        }",
              "        .card-title {",
              "            margin: 0;",
              "            font-size: 8.3px;",
              "            font-weight: 600;",
              "            color: #333;",
              "        }",
              "        .card-subtitle {",
              "            margin: 5px 0 0;",
              "            font-size: 10.2px;",
              "            color: #003449;",
              "            font-weight: 500;",
              "        }",
              "        .card-subtitle-small {",
              "            margin: 2px 0 0;",
              "            font-size: 10.5px;",
              "            color: #666;",
              "            font-weight: 400;",
              "        }",
              "        .price-tag {",
              "            position: absolute;",
              "            top: 6px;",
              "            right: 6px;",
              "            background-color: rgba(0, 120, 212, 0.9);",
              "            color: white;",
              "            padding: 3px 6px;",
              "            border-radius: 14px;",
              "            font-size: 9px;",
              "            font-weight: bold;",
              "        }",
              "    </style>",
              "</head>",
              "<body>",
              "    <div class='card'>",
              "        <div class='card-image-container'>",
              "            <img src='\"&_Imagem&\"' alt='\"&_Posicao&\"' class='card-image'>",
              "            <span class='price-tag'>\"&_GolsTemporada&\"</span>",
              "        </div>",
              "        <div class='card-content'>",
              "            <h2 class='card-title'>\"&_Posicao&\"</h2>",
              "            <p class='card-subtitle'> \"&_JogadorNome & \" </p>",
              "            <p class='card-subtitle-small'> \"&_Nacionalidade&\"</p>",
              "            <p class='card-subtitle-small'> \"&_Nascimento&\"</p>",
              "        </div>",
              "    </div>",
              "</body>",
              "</html>\"",
              ""
            ],
            "lineageTag": "a908d202-904d-4027-b157-5534c69eeae1"
          },
          {
            "name": "JogadorComMaisGols",
            "expression": [
              "",
              "VAR TabelaResumo = ",
              "    SUMMARIZE(",
              "        'campeonato-brasileiro-gols', ",
              "        'campeonato-brasileiro-gols'[clube], ",
              "        'campeonato-brasileiro-gols'[atleta], ",
              "        \"TotalGols\", ",
              "        CALCULATE(",
              "            COUNTROWS('campeonato-brasileiro-gols'),",
              "            'campeonato-brasileiro-gols'[tipo_de_gol] <> \"Gol Contra\"",
              "        )",
              "    )",
              "VAR JogadorComMais = ",
              "    TOPN(1, TabelaResumo, [TotalGols], DESC)",
              "RETURN",
              "    SELECTCOLUMNS(JogadorComMais, \"Atleta\", 'campeonato-brasileiro-gols'[atleta])",
              ""
            ],
            "lineageTag": "48d8e423-d1cd-4dcd-8ef9-3e2a18cabc92"
          },
          {
            "name": "Artilheiro1",
            "expression": [
              "",
              "VAR JogadorComMais = ",
              "    TOPN(1, TabelaGolsPorClube, TabelaGolsPorClube[TotalGols], DESC, TabelaGolsPorClube[atleta], ASC)  -- Desempate pelo nome (alfabeticamente)",
              "RETURN",
              "    SELECTCOLUMNS(JogadorComMais, \"Atleta\", TabelaGolsPorClube[atleta])",
              ""
            ],
            "lineageTag": "d9e11ff6-cfa0-466f-a857-d9b71ca1ca5e"
          },
          {
            "name": "Cards_Artilheiro1",
            "expression": [
              "",
              "VAR _JogadorComMais =  [Artilheiro1]",
              "VAR _Imagem = COALESCE(CALCULATE(MIN(dim_jogadores[Imagem]), dim_jogadores[atleta] = _JogadorComMais), \"https://i.pinimg.com/736x/7c/cb/01/7ccb010d8fddc4bcd84587ef3c34d100.jpg\")",
              "VAR _Posicao = CALCULATE(MIN(dim_jogadores[Posição]), dim_jogadores[atleta] = _JogadorComMais) ",
              "VAR _JogadorNome = _JogadorComMais",
              "VAR _Nascimento = CALCULATE(MIN(dim_jogadores[Dt Nascimento]), dim_jogadores[atleta] = _JogadorComMais) ",
              "VAR _Nacionalidade = CALCULATE(MIN(dim_jogadores[Nacionalidade]), dim_jogadores[atleta] = _JogadorComMais)  ",
              "VAR _GolsTemporada = CALCULATE(count('campeonato-brasileiro-gols'[partida_id]), dim_jogadores[atleta] = _JogadorNome)",
              "",
              "RETURN",
              "",
              "\"<!DOCTYPE html>",
              "<html lang='en'>",
              "<head>",
              "    <meta charset='UTF-8'>",
              "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>",
              "    <title>Compact Gallery Card</title>",
              "    <style>",
              "        body {",
              "            margin: 0;",
              "            padding: 8px;",
              "            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;",
              "        }",
              "        .card {",
              "            width: 177px; ",
              "            margin: 12px auto;",
              "            border-radius: 10px;",
              "            overflow: hidden;",
              "            box-shadow: 0 2px 6px rgba(0, 0, 0, 0.1);",
              "            transition: transform 0.3s ease, box-shadow 0.3s ease;",
              "            background-color: #ffffff;",
              "}",
              "        .card:hover {",
              "            transform: translateY(-6px);",
              "            box-shadow: 0 4px 14px rgba(0, 0, 0, 0.15);",
              "        }",
              "        .card-image-container {",
              "            position: relative;",
              "            height: 192px;",
              "            overflow: hidden;",
              "        }",
              "        .card-image {",
              "            width: 100%;",
              "            height: 100%;",
              "            object-fit: cover;",
              "            transition: transform 0.3s ease;",
              "        }",
              "        .card:hover .card-image {",
              "            transform: scale(1.05);",
              "        }",
              "        .card-content {",
              "            padding: 10px;",
              "        }",
              "        .card-title {",
              "            margin: 0;",
              "            font-size: 8.3px;",
              "            font-weight: 600;",
              "            color: #333;",
              "        }",
              "        .card-subtitle {",
              "            margin: 5px 0 0;",
              "            font-size: 10.2px;",
              "            color: #003449;",
              "            font-weight: 500;",
              "        }",
              "        .card-subtitle-small {",
              "            margin: 2px 0 0;",
              "            font-size: 10.5px;",
              "            color: #666;",
              "            font-weight: 400;",
              "        }",
              "        .price-tag {",
              "            position: absolute;",
              "            top: 6px;",
              "            right: 6px;",
              "            background-color: rgba(0, 120, 212, 0.9);",
              "            color: white;",
              "            padding: 3px 6px;",
              "            border-radius: 14px;",
              "            font-size: 9px;",
              "            font-weight: bold;",
              "        }",
              "    </style>",
              "</head>",
              "<body>",
              "    <div class='card'>",
              "        <div class='card-image-container'>",
              "            <img src='\"&_Imagem&\"' alt='\"&_Posicao&\"' class='card-image'>",
              "            <span class='price-tag'>\"&_GolsTemporada&\"</span>",
              "        </div>",
              "        <div class='card-content'>",
              "            <h2 class='card-title'>\"&_Posicao&\"</h2>",
              "            <p class='card-subtitle'> \"&_JogadorNome & \" </p>",
              "            <p class='card-subtitle-small'> \"&_Nacionalidade&\"</p>",
              "            <p class='card-subtitle-small'> \"&_Nascimento&\"</p>",
              "        </div>",
              "    </div>",
              "</body>",
              "</html>\""
            ],
            "lineageTag": "0bddcb4d-927d-4c56-ba8a-e3fc4e8e1cc6"
          },
          {
            "name": "Artilheiro2",
            "expression": [
              "",
              "VAR JogadoresOrdenados =",
              "    TOPN(",
              "        2,",
              "        TabelaGolsPorClube,",
              "        TabelaGolsPorClube[TotalGols], DESC,",
              "        TabelaGolsPorClube[atleta], ASC",
              "    )",
              "",
              "VAR Segundo =",
              "    TOPN(",
              "        1,",
              "        EXCEPT(",
              "            JogadoresOrdenados,",
              "            TOPN(",
              "                1,",
              "                JogadoresOrdenados,",
              "                TabelaGolsPorClube[TotalGols], DESC,",
              "                TabelaGolsPorClube[atleta], ASC",
              "            )",
              "        ),",
              "        TabelaGolsPorClube[TotalGols], DESC,",
              "        TabelaGolsPorClube[atleta], ASC",
              "    )",
              "",
              "RETURN",
              "    SELECTCOLUMNS(Segundo, \"Atleta\", TabelaGolsPorClube[atleta])",
              ""
            ],
            "lineageTag": "62c3e8c7-6a4c-4882-a107-7c1e55e79f36"
          },
          {
            "name": "Cards_Artilheiro2",
            "expression": [
              "",
              "VAR _JogadorComMais =  [Artilheiro2]",
              "",
              "VAR _Imagem = COALESCE(CALCULATE(MIN(dim_jogadores[Imagem]), dim_jogadores[atleta] = _JogadorComMais), \"https://i.pinimg.com/736x/7c/cb/01/7ccb010d8fddc4bcd84587ef3c34d100.jpg\")",
              "VAR _Posicao = CALCULATE(MIN(dim_jogadores[Posição]), dim_jogadores[atleta] = _JogadorComMais) ",
              "VAR _JogadorNome = _JogadorComMais",
              "VAR _Nascimento = CALCULATE(MIN(dim_jogadores[Dt Nascimento]), dim_jogadores[atleta] = _JogadorComMais) ",
              "VAR _Nacionalidade = CALCULATE(MIN(dim_jogadores[Nacionalidade]), dim_jogadores[atleta] = _JogadorComMais)  ",
              "VAR _GolsTemporada = CALCULATE(sum(TabelaGolsPorClube[TotalGols]), TabelaGolsPorClube[atleta] = _JogadorNome )",
              "",
              "RETURN",
              "",
              "\"<!DOCTYPE html>",
              "<html lang='en'>",
              "<head>",
              "    <meta charset='UTF-8'>",
              "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>",
              "    <title>Compact Gallery Card</title>",
              "    <style>",
              "        body {",
              "            margin: 0;",
              "            padding: 8px;",
              "            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;",
              "        }",
              "        .card {",
              "            width: 177px; ",
              "            margin: 12px auto;",
              "            border-radius: 10px;",
              "            overflow: hidden;",
              "            box-shadow: 0 2px 6px rgba(0, 0, 0, 0.1);",
              "            transition: transform 0.3s ease, box-shadow 0.3s ease;",
              "            background-color: #ffffff;",
              "        }",
              "        .card:hover {",
              "            transform: translateY(-6px);",
              "            box-shadow: 0 4px 14px rgba(0, 0, 0, 0.15);",
              "        }",
              "        .card-image-container {",
              "            position: relative;",
              "            height: 192px;",
              "            overflow: hidden;",
              "        }",
              "        .card-image {",
              "            width: 100%;",
              "            height: 100%;",
              "            object-fit: cover;",
              "            transition: transform 0.3s ease;",
              "        }",
              "        .card:hover .card-image {",
              "            transform: scale(1.05);",
              "        }",
              "        .card-content {",
              "            padding: 10px;",
              "        }",
              "        .card-title {",
              "            margin: 0;",
              "            font-size: 8.3px;",
              "            font-weight: 600;",
              "            color: #333;",
              "        }",
              "        .card-subtitle {",
              "            margin: 5px 0 0;",
              "            font-size: 10.2px;",
              "            color: #003449;",
              "            font-weight: 500;",
              "        }",
              "        .card-subtitle-small {",
              "            margin: 2px 0 0;",
              "            font-size: 10.5px;",
              "            color: #666;",
              "            font-weight: 400;",
              "        }",
              "        .price-tag {",
              "            position: absolute;",
              "            top: 6px;",
              "            right: 6px;",
              "            background-color: rgba(0, 120, 212, 0.9);",
              "            color: white;",
              "            padding: 3px 6px;",
              "            border-radius: 14px;",
              "            font-size: 9px;",
              "            font-weight: bold;",
              "        }",
              "    </style>",
              "</head>",
              "<body>",
              "    <div class='card'>",
              "        <div class='card-image-container'>",
              "            <img src='\"&_Imagem&\"' alt='\"&_Posicao&\"' class='card-image'>",
              "            <span class='price-tag'>\"&_GolsTemporada&\"</span>",
              "        </div>",
              "        <div class='card-content'>",
              "            <h2 class='card-title'>\"&_Posicao&\"</h2>",
              "            <p class='card-subtitle'> \"&_JogadorNome & \" </p>",
              "            <p class='card-subtitle-small'> \"&_Nacionalidade&\"</p>",
              "            <p class='card-subtitle-small'> \"&_Nascimento&\"</p>",
              "        </div>",
              "    </div>",
              "</body>",
              "</html>\""
            ],
            "lineageTag": "14f53f4a-3a0c-40ac-9e1f-d3ca57cf7fad"
          },
          {
            "name": "Artilheiro3",
            "expression": [
              "",
              "VAR JogadoresOrdenados =",
              "    TOPN(",
              "        3,",
              "        TabelaGolsPorClube,",
              "        TabelaGolsPorClube[TotalGols], DESC,",
              "        TabelaGolsPorClube[atleta], ASC",
              "    )",
              "",
              "VAR Terceiro =",
              "    TOPN(",
              "        1,",
              "        EXCEPT(",
              "            JogadoresOrdenados,",
              "            TOPN(",
              "                2,",
              "                JogadoresOrdenados,",
              "                TabelaGolsPorClube[TotalGols], DESC,",
              "                TabelaGolsPorClube[atleta], ASC",
              "            )",
              "        ),",
              "        TabelaGolsPorClube[TotalGols], DESC,",
              "        TabelaGolsPorClube[atleta], ASC",
              "    )",
              "",
              "RETURN",
              "    SELECTCOLUMNS(Terceiro, \"Atleta\", TabelaGolsPorClube[atleta])",
              ""
            ],
            "lineageTag": "3e86b59a-fdcc-4904-bdd3-8983d8dec648"
          },
          {
            "name": "Cards_Artilheiro3",
            "expression": [
              "",
              "VAR _JogadorComMais =  [Artilheiro3]",
              "",
              "VAR _Imagem = COALESCE(CALCULATE(MIN(dim_jogadores[Imagem]), dim_jogadores[atleta] = _JogadorComMais), \"https://i.pinimg.com/736x/7c/cb/01/7ccb010d8fddc4bcd84587ef3c34d100.jpg\")",
              "VAR _Posicao = CALCULATE(MIN(dim_jogadores[Posição]), dim_jogadores[atleta] = _JogadorComMais) ",
              "VAR _JogadorNome = _JogadorComMais",
              "VAR _Nascimento = CALCULATE(MIN(dim_jogadores[Dt Nascimento]), dim_jogadores[atleta] = _JogadorComMais) ",
              "VAR _Nacionalidade = CALCULATE(MIN(dim_jogadores[Nacionalidade]), dim_jogadores[atleta] = _JogadorComMais)  ",
              "VAR _GolsTemporada = CALCULATE(sum(TabelaGolsPorClube[TotalGols]), TabelaGolsPorClube[atleta] = _JogadorNome )",
              "",
              "RETURN",
              "",
              "\"<!DOCTYPE html>",
              "<html lang='en'>",
              "<head>",
              "    <meta charset='UTF-8'>",
              "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>",
              "    <title>Compact Gallery Card</title>",
              "    <style>",
              "        body {",
              "            margin: 0;",
              "            padding: 8px;",
              "            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;",
              "        }",
              "        .card {",
              "            width: 177px; ",
              "            margin: 12px auto;",
              "            border-radius: 10px;",
              "            overflow: hidden;",
              "            box-shadow: 0 2px 6px rgba(0, 0, 0, 0.1);",
              "            transition: transform 0.3s ease, box-shadow 0.3s ease;",
              "            background-color: #ffffff;",
              "        }",
              "        .card:hover {",
              "            transform: translateY(-6px);",
              "            box-shadow: 0 4px 14px rgba(0, 0, 0, 0.15);",
              "        }",
              "        .card-image-container {",
              "            position: relative;",
              "            height: 192px;",
              "            overflow: hidden;",
              "        }",
              "        .card-image {",
              "            width: 100%;",
              "            height: 100%;",
              "            object-fit: cover;",
              "            transition: transform 0.3s ease;",
              "        }",
              "        .card:hover .card-image {",
              "            transform: scale(1.05);",
              "        }",
              "        .card-content {",
              "            padding: 10px;",
              "        }",
              "        .card-title {",
              "            margin: 0;",
              "            font-size: 8.3px;",
              "            font-weight: 600;",
              "            color: #333;",
              "        }",
              "        .card-subtitle {",
              "            margin: 5px 0 0;",
              "            font-size: 10.2px;",
              "            color: #003449;",
              "            font-weight: 500;",
              "        }",
              "        .card-subtitle-small {",
              "            margin: 2px 0 0;",
              "            font-size: 10.5px;",
              "            color: #666;",
              "            font-weight: 400;",
              "        }",
              "        .price-tag {",
              "            position: absolute;",
              "            top: 6px;",
              "            right: 6px;",
              "            background-color: rgba(0, 120, 212, 0.9);",
              "            color: white;",
              "            padding: 3px 6px;",
              "            border-radius: 14px;",
              "            font-size: 9px;",
              "            font-weight: bold;",
              "        }",
              "    </style>",
              "</head>",
              "<body>",
              "    <div class='card'>",
              "        <div class='card-image-container'>",
              "            <img src='\"&_Imagem&\"' alt='\"&_Posicao&\"' class='card-image'>",
              "            <span class='price-tag'>\"&_GolsTemporada&\"</span>",
              "        </div>",
              "        <div class='card-content'>",
              "            <h2 class='card-title'>\"&_Posicao&\"</h2>",
              "            <p class='card-subtitle'> \"&_JogadorNome & \" </p>",
              "            <p class='card-subtitle-small'> \"&_Nacionalidade&\"</p>",
              "            <p class='card-subtitle-small'> \"&_Nascimento&\"</p>",
              "        </div>",
              "    </div>",
              "</body>",
              "</html>\""
            ],
            "lineageTag": "7be5f145-9c60-41fe-bbba-1c15ad787444"
          },
          {
            "name": "teste_cor",
            "expression": [
              "",
              "CALCULATE(",
              "    SELECTEDVALUE(dim_cores[Código Hexadecimal]), ",
              "    FILTER(",
              "        dim_cores, ",
              "        dim_cores[Cor] = SELECTEDVALUE(dim_clubes[Cores])",
              "    )",
              ")",
              ""
            ],
            "lineageTag": "0e66e814-6b7c-4d60-b378-b79a6a5574d3"
          },
          {
            "name": "partidas2",
            "expression": [
              "",
              "CONCATENATEX(",
              "    'campeonato-brasileiro-full',  ",
              "    VAR _DataHora = FORMAT('campeonato-brasileiro-full'[data], \"DD/MM/YYYY\") & \" \" & FORMAT('campeonato-brasileiro-full'[hora], \"HH:mm\")",
              "    VAR _Mandante = 'campeonato-brasileiro-full'[mandante]",
              "    VAR _MandantePlacar = 'campeonato-brasileiro-full'[mandante_Placar]",
              "    VAR _Visitante = 'campeonato-brasileiro-full'[visitante]",
              "    VAR _VisitantePlacar = 'campeonato-brasileiro-full'[visitante_Placar]",
              "    VAR _Arena = 'campeonato-brasileiro-full'[arena]",
              "    VAR _Estado = 'campeonato-brasileiro-full'[mandante_Estado]",
              "    VAR _PartidaID = 'campeonato-brasileiro-full'[id]",
              "",
              "    -- Gols do mandante",
              "    VAR _GolsMandante = ",
              "        CALCULATETABLE(",
              "            VALUES('campeonato-brasileiro-gols'[atleta]),",
              "            TREATAS({_PartidaID}, 'campeonato-brasileiro-gols'[partida_id]),",
              "            'campeonato-brasileiro-gols'[clube] = _Mandante",
              "        )",
              "",
              "    VAR _TextoGolsMandante = ",
              "        IF(_MandantePlacar <> 0,",
              "            CONCATENATEX(_GolsMandante, 'campeonato-brasileiro-gols'[atleta], UNICHAR(10)),",
              "            \"\"",
              "        )",
              "",
              "    -- Gols do visitante",
              "    VAR _GolsVisitante = ",
              "        CALCULATETABLE(",
              "            VALUES('campeonato-brasileiro-gols'[atleta]),",
              "            TREATAS({_PartidaID}, 'campeonato-brasileiro-gols'[partida_id]),",
              "            'campeonato-brasileiro-gols'[clube] = _Visitante",
              "        )",
              "",
              "    VAR _TextoGolsVisitante = ",
              "        IF(_VisitantePlacar <> 0,",
              "            CONCATENATEX(_GolsVisitante, 'campeonato-brasileiro-gols'[atleta], UNICHAR(10)),",
              "            \"\"",
              "        )",
              "",
              "    -- Seleciona a cor e aplica uma cor padrão caso não tenha valor",
              "    VAR _cores = IF(",
              "        NOT(ISBLANK(CALCULATE(",
              "    SELECTEDVALUE(dim_cores[Código Hexadecimal]), ",
              "    FILTER(",
              "        dim_cores, ",
              "        dim_cores[Cor] = SELECTEDVALUE(dim_clubes[Cores])",
              "    )",
              "))),",
              "        CALCULATE(",
              "            SELECTEDVALUE(dim_cores[Código Hexadecimal]), ",
              "            FILTER(",
              "        dim_cores, ",
              "        dim_cores[Cor] = SELECTEDVALUE(dim_clubes[Cores])",
              "    )",
              "),",
              "        \"#000000\"  -- Cor padrão cinza caso não haja cor válida",
              "    )",
              "",
              "    -- Formatação do HTML com a cor aplicada",
              "    RETURN",
              "    \"<div style='background-color: \" & _cores & \"; padding: 8px; margin-bottom: 8px; border: 2px solid \" & _cores & \"; border-radius: 5px; box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3); font-size: 75%;'>\" & ",
              "",
              "    \"<div style='text-align: center; color: \" & IF(_cores = \"#FFFFFF\", \"#000000\", \"#f1f1f1\") & \"; font-size: 14px;'>\" & ",
              "    _DataHora & ",
              "    \"</div>\" &",
              "",
              "    \"<div style='text-align: center; font-size: 16px; font-weight: bold; color: \" & IF(_cores = \"#FFFFFF\", \"#000000\", \"#f1f1f1\") & \";'>\" & ",
              "    _Mandante & \" \" & ",
              "    _MandantePlacar & \" - \" & ",
              "    _VisitantePlacar & \" \" & ",
              "    _Visitante & ",
              "    \"</div>\" &",
              "",
              "    \"<div style='text-align: center; font-size: 12px; color: #e0e0e0;'> \" & _Arena & \" (\" & _Estado & \")\" & \"</div>\" &",
              "",
              "    IF(_MandantePlacar <> 0,",
              "        \"<div style='text-align: center; white-space: pre-line; color: \" & IF(_cores = \"#FFFFFF\", \"#000000\", \"#f1f1f1\") & \";'>\" & _TextoGolsMandante & \"</div>\",",
              "        \"\"",
              "    ) &",
              "",
              "    IF(_VisitantePlacar <> 0,",
              "        \"<div style='text-align: center; white-space: pre-line; color: \" & IF(_cores = \"#FFFFFF\", \"#000000\", \"#f1f1f1\") & \";'>\" & _TextoGolsVisitante & \"</div>\",",
              "        \"\"",
              "    ) &",
              "",
              "    \"</div>\",",
              "    UNICHAR(10)",
              ")",
              ""
            ],
            "lineageTag": "2de376f3-ebf5-494b-a026-f2b6365d3fe2"
          },
          {
            "name": "JogadoresGolMandante",
            "expression": [
              "",
              "VAR _Mandante = MAX('campeonato-brasileiro-full'[mandante])",
              "",
              "VAR _AtletasGolMandante = ",
              "    FILTER(",
              "        'campeonato-brasileiro-gols',",
              "        'campeonato-brasileiro-gols'[clube] = _Mandante",
              "    )",
              "",
              "RETURN ",
              "CONCATENATEX(",
              "    _AtletasGolMandante,",
              "    FORMAT('campeonato-brasileiro-gols'[minuto], \"0\") & \"\"\" \" & 'campeonato-brasileiro-gols'[atleta],",
              "    UNICHAR(10),",
              "    'campeonato-brasileiro-gols'[minuto],",
              "    ASC",
              ")",
              ""
            ],
            "lineageTag": "790038e6-e2e7-4b5b-94e2-45fabbfc1c6a"
          },
          {
            "name": "indice_cor",
            "expression": [
              "CALCULATE(",
              "    SELECTEDVALUE(dim_cores[Índice]), ",
              "    FILTER(",
              "        dim_cores, ",
              "        dim_cores[Cor] = SELECTEDVALUE(dim_clubes[Cores])",
              "    )",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "00524ddc-3ed0-41ee-9b24-011683019ff2"
          },
          {
            "name": "_pontosAno",
            "expression": [
              "",
              "VAR TemFiltroTime = ISFILTERED('full - unpivot'[Time])",
              "RETURN",
              "    IF(",
              "        TemFiltroTime,",
              "        SUM('full - unpivot'[Pontos]),",
              "        CALCULATE(",
              "            MAXX(",
              "                VALUES('full - unpivot'[Time]),",
              "                CALCULATE(SUM('full - unpivot'[Pontos]))",
              "            )",
              "        )",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "a893e4a5-ee7d-47bc-9820-4e1feb8061be"
          },
          {
            "name": "_golsProAno",
            "expression": [
              "",
              "VAR TemFiltroTime = ISFILTERED('full - unpivot'[Time])",
              "RETURN",
              "    IF(",
              "        TemFiltroTime,",
              "        SUM('full - unpivot'[gols_pro]),",
              "        CALCULATE(",
              "            MAXX(",
              "                VALUES('full - unpivot'[Time]),",
              "                CALCULATE(SUM('full - unpivot'[gols_pro]))",
              "            )",
              "        )",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "90644301-c73e-488a-8f7e-a2b07e131931"
          },
          {
            "name": "_golsContraAno",
            "expression": [
              "",
              "VAR TemFiltroTime = ISFILTERED('full - unpivot'[Time])",
              "RETURN",
              "    IF(",
              "        TemFiltroTime,",
              "        SUM('full - unpivot'[gols_contra]),",
              "        CALCULATE(",
              "            MAXX(",
              "                VALUES('full - unpivot'[Time]),",
              "                CALCULATE(SUM('full - unpivot'[gols_contra]))",
              "            )",
              "        )",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "d0344609-7816-43b6-8d92-9f77ff130bc7"
          },
          {
            "name": "_golsSGAno",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR TemFiltroTime = ISFILTERED('full - unpivot'[Time])",
              "RETURN",
              "    IF(",
              "        TemFiltroTime,",
              "        SUM('full - unpivot'[Saldo Gols]),",
              "        CALCULATE(",
              "            MAXX(",
              "                VALUES('full - unpivot'[Time]),",
              "                CALCULATE(SUM('full - unpivot'[Saldo Gols]))",
              "            )",
              "        )",
              "    )"
            ],
            "lineageTag": "4d5f7f66-fb6a-4e8b-b1d9-ebee0f6105e4"
          }
        ],
        "partitions": [
          {
            "name": "Tabela",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"lY7LDoIwEEV/xXTNUKpQH4nxF1y5IYRUGKBqaR0K/r4UTVy7uauTc26eszOhtytcXUn1lWUR67x3w4Fzbdq4IUSn73FlDZ9mjnAAR2j0aHhjySh4jqomVSto59XYe4Qa4SMDp0gF3ttSiJ1YpyCEkFl8c+3pddzIhBVRzi5IBh9dOLGw/3wY+9qG4K++KABh+lpLkchMbCWk+0SGMiuKNw==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Coluna 1\" = _t, #\"Coluna 2\" = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Coluna 1\", type text}, {\"Coluna 2\", type text}}),",
                "    #\"Texto Aparado\" = Table.TransformColumns(#\"Tipo Alterado\",{{\"Coluna 1\", Text.Trim, type text}}),",
                "    #\"Texto Limpo\" = Table.TransformColumns(#\"Texto Aparado\",{{\"Coluna 1\", Text.Clean, type text}})",
                "in",
                "    #\"Texto Limpo\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_2ea599c2-7a12-48e5-845a-02093c9b8bcd",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "43a30e12-f24b-4e46-8a72-624aecf1a644",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c73e4eac-04fa-4412-bd4e-25128e69c9cc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d6861655-fe22-434a-8131-bddb10258cab",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "38eeb210-1e17-4d89-ba55-7d74378c9854",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e7c4d3cf-f167-4f03-9e49-b00d988fedd0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "6cdd55e1-98b3-4f18-9d79-196a478ca35f",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e441daf1-e41e-4985-871d-b7370e03403b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "129fefe4-f0bc-4a4f-ba96-d3ce98295cdf",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "e82af972-8b3d-473a-91ab-f37cb24c0d3a",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "51fcfef1-691f-44e2-9a28-8fb43bba7b12",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "17e54cd9-8c7a-4277-bcc6-612984809af8",
                "ordinal": 3
              }
            ],
            "lineageTag": "ceba009a-073b-4d6b-9dbb-5004b829ab6d"
          }
        ],
        "isHidden": true,
        "lineageTag": "f20becf6-8a1c-44a1-a7c5-455d08b51667",
        "partitions": [
          {
            "name": "LocalDateTable_2ea599c2-7a12-48e5-845a-02093c9b8bcd",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dim_clubes'[Fundacao])), 1, 1), Date(Year(MAX('dim_clubes'[Fundacao])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "fct_classificacao",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "69c9dc6adcd04c4d9c2c6f35b9d53761"
          }
        ],
        "columns": [
          {
            "name": "time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a8ad2e6d-33e3-4c40-92ae-3af6584a84b9",
            "sourceColumn": "full - unpivot[time]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "TotalPontos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6205ee72-9e4a-42d3-b45a-56bd677066b7",
            "sourceColumn": "[TotalPontos]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ranking_times",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "VAR AnoAtual = [Ano]",
              "RETURN",
              "RANKX(",
              "    FILTER(",
              "        fct_classificacao,",
              "        [Ano] = AnoAtual",
              "    ),",
              "     fct_classificacao[TotalPontos] * 1000000 +",
              "     fct_classificacao[TotalVitorias] * 10000 +",
              "     fct_classificacao[SaldoGols] * 100 +",
              "     fct_classificacao[GolsPro],",
              "    ,",
              "    DESC,",
              "    DENSE",
              ")"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "6cc7a3fd-af2c-4595-8c43-fa29368d322c",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "TotalVitorias",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "7f893e42-1859-45ea-a7dc-7a9895042a15",
            "sourceColumn": "[TotalVitorias]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "SaldoGols",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a6e9ed28-7e9f-41bb-859c-d599fa9526f8",
            "sourceColumn": "[SaldoGols]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "TotalJogos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c366fd43-4aba-4ac9-92d6-bcadc973975a",
            "sourceColumn": "[TotalJogos]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "TotalDerrotas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c925ee07-fdc5-4026-99f6-29b2ffddb289",
            "sourceColumn": "[TotalDerrotas]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "TotalEmpates",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "1af3fced-06fb-4ed5-99ed-fe8a49dbad6f",
            "sourceColumn": "[TotalEmpates]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "GolsPro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "88a16f07-5506-4e8d-83fa-d205e25251c4",
            "sourceColumn": "[GolsPro]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "GolsContra",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "55609c83-d5da-4af3-9140-1f4f9d5ebf1f",
            "sourceColumn": "[GolsContra]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f8194a54-83ee-4ecb-bde2-c98acf17babe",
            "sourceColumn": "full - unpivot[Ano]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Série",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "7f0a72aa-cb3b-469c-bd5b-5d494d5c1280",
            "sourceColumn": "full - unpivot[Série]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "542f90ee-9360-4b32-8af8-77287be71bf2",
        "measures": [
          {
            "name": "Medida",
            "annotations": [
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ],
            "lineageTag": "c8c216c6-b9b2-4bfa-b0cc-160a5c9c59c3"
          },
          {
            "name": "teste_game _",
            "expression": [
              "",
              "\"<div style='font-family: Arial, sans-serif; padding: 20px; text-align: center;'>",
              "    <h2>Pergunta: Qual é a capital da França?</h2>",
              "    <div>",
              "        <button>Paris</button>",
              "        <button>Londres</button>",
              "        <button>Roma</button>",
              "    </div>",
              "    <p style='font-size: 18px;'>Sua resposta: \" & ",
              "     ",
              "    \"</p>",
              "</div>\"",
              ""
            ],
            "lineageTag": "36a95905-6d7b-4f33-adc9-870fd480b087"
          },
          {
            "name": "_PosicaoMaximaAno",
            "expression": [
              "",
              "CALCULATE(",
              "    MIN(fct_classificacao[Ranking_times]))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "8f0b018b-6bd3-499c-bb3f-654b0df0cd89"
          }
        ],
        "partitions": [
          {
            "name": "fct_classificacao",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "SUMMARIZE(",
                "    FILTER(",
                "        'full - unpivot',",
                "        VAR AnoData = YEAR('full - unpivot'[Data])",
                "        VAR MesData = MONTH('full - unpivot'[Data])",
                "        RETURN",
                "            IF(",
                "                AnoData = 2021 && MesData < 3, ",
                "                2020, ",
                "                AnoData",
                "            ) = 'full - unpivot'[Ano] ",
                "    ),",
                "    'full - unpivot'[time],",
                "    'full - unpivot'[Ano],",
                "    'full - unpivot'[Série],",
                "    \"TotalJogos\", DISTINCTCOUNT('full - unpivot'[ID]),",
                "    \"TotalPontos\", SUM('full - unpivot'[Pontos]),",
                "    \"TotalVitorias\", CALCULATE(DISTINCTCOUNT('full - unpivot'[ID]), 'full - unpivot'[R] = \"V\"),",
                "    \"TotalDerrotas\", CALCULATE(DISTINCTCOUNT('full - unpivot'[ID]), 'full - unpivot'[R] = \"D\"),",
                "    \"TotalEmpates\", CALCULATE(DISTINCTCOUNT('full - unpivot'[ID]), 'full - unpivot'[R] = \"E\"),",
                "    \"GolsPro\", SUM('full - unpivot'[gols_pro]),",
                "    \"GolsContra\", SUM('full - unpivot'[gols_contra]),",
                "    \"SaldoGols\", SUM('full - unpivot'[Saldo Gols])",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dim_jogadores",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "atleta",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9073d774-102c-4868-a9d4-47daaf487170",
            "sourceColumn": "atleta",
            "summarizeBy": "none"
          },
          {
            "name": "Imagem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "491eb021-c823-48db-b409-077e532542a8",
            "sourceColumn": "Imagem",
            "summarizeBy": "none"
          },
          {
            "name": "Dt Nascimento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "0015dbc2-50a8-4dfa-bf92-0d36175a7eca",
            "sourceColumn": "Dt Nascimento",
            "summarizeBy": "none"
          },
          {
            "name": "Local Nascimento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "885d01b3-c9b6-463a-a566-c539fa06eacc",
            "sourceColumn": "Local Nascimento",
            "summarizeBy": "none"
          },
          {
            "name": "Nacionalidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9a23b68c-f979-4f35-bcdb-26fd58adfacb",
            "sourceColumn": "Nacionalidade",
            "summarizeBy": "none"
          },
          {
            "name": "Posição",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f0b4f8d7-d951-45ec-99e2-daf96bc2fd01",
            "sourceColumn": "Posição",
            "summarizeBy": "none"
          },
          {
            "name": "Situação",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a17182c5-3120-41ae-a453-e3569108cb65",
            "sourceColumn": "Situação",
            "summarizeBy": "none"
          },
          {
            "name": "Clube Atual",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cde7d4af-5482-43d1-870c-fd4cf2db6d50",
            "sourceColumn": "Clube Atual",
            "summarizeBy": "none"
          },
          {
            "name": "Biografia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8434654-5bc0-4cad-b03c-9ff435e8afae",
            "sourceColumn": "Biografia",
            "summarizeBy": "none"
          },
          {
            "name": "Pé-Preferencial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "27dbbcd6-3d7f-4dd1-bbb8-c3b9685b5cf4",
            "sourceColumn": "Pé-Preferencial",
            "summarizeBy": "none"
          },
          {
            "name": "Nome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7f00dde3-38e5-4d14-aa17-a7e35e5ea9d9",
            "sourceColumn": "Nome",
            "summarizeBy": "none"
          },
          {
            "name": "clube",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "54fc4170-1f6f-4693-9d18-55caf8809680",
            "sourceColumn": "clube",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "33aeea26-f2b9-49e3-b904-0f873a42d10d",
        "partitions": [
          {
            "name": "dim_jogadores",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Excel.Workbook(File.Contents(\"C:\\Users\\MSI\\Documents\\PBI\\Brasileirao\\jogadores.xlsx\"), null, true),",
                "    campeonato_brasileiro_gols_Table = Fonte{[Item=\"campeonato_brasileiro_gols\",Kind=\"Table\"]}[Data],",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(campeonato_brasileiro_gols_Table,{{\"clube\", type text}, {\"atleta\", type text}, {\"Imagem\", type text}, {\"Dt Nascimento\", type date}, {\"Local Nascimento\", type text}, {\"Nacionalidade\", type text}, {\"Posição\", type text}, {\"Pé-Preferencial\", type text}, {\"Situação\", type text}, {\"Clube Atual\", type text}, {\"Biografia\", type text}}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Tipo Alterado\", {\"atleta\"})",
                "in",
                "    #\"Duplicatas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "TabelaGolsPorClube",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "e31bb0eb488e423985b9b809860c5dc4"
          }
        ],
        "columns": [
          {
            "name": "clube",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ef81f6ff-2cb2-4313-9128-d6ee3c22707b",
            "sourceColumn": "campeonato-brasileiro-gols[clube]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "atleta",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "a5c70e03-3df3-42cb-a2ef-c6f81cf7fe11",
            "sourceColumn": "campeonato-brasileiro-gols[atleta]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "TotalGols",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5a2a4918-c726-41e7-ab4f-7b2555bb4dbe",
            "sourceColumn": "[TotalGols]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "7e839f21-c458-4602-befe-2735165dda1c",
        "partitions": [
          {
            "name": "TabelaGolsPorClube",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "SUMMARIZE(",
                "    'campeonato-brasileiro-gols', ",
                "    'campeonato-brasileiro-gols'[clube], ",
                "    'campeonato-brasileiro-gols'[atleta], ",
                "    \"TotalGols\", ",
                "    CALCULATE(",
                "        COUNTROWS('campeonato-brasileiro-gols'),",
                "        'campeonato-brasileiro-gols'[tipo_de_gol] <> \"Gol Contra\"",
                "    )",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dCalendar",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "4a732000d2d9491986a3ede10c077508"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isKey": true,
            "isNameInferred": true,
            "lineageTag": "68b70bed-2639-45dc-9d2d-12852eefe449",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6a81c3b7-8815-4f68-a8ab-3b1499eddbba",
            "sourceColumn": "[Ano]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d60158f6-cda9-4198-b934-154d6c8079c8",
            "sourceColumn": "[Mês]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "NomeMês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "2a1c826f-1010-4a63-9a87-19b0f2d7594a",
            "sourceColumn": "[NomeMês]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "598d3e0a-56e9-4642-9a79-31a254bbd318",
            "sourceColumn": "[Trimestre]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5b61496b-d1b8-4ed4-b667-ce8ff8324729",
            "sourceColumn": "[Dia]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Nome do Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0a6688f5-db52-46b0-89cc-072b23ab52a7",
            "sourceColumn": "[Nome do Dia]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano-Campeonato",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "bc9f44d2-f67c-4be9-b303-1a529c11ae13",
            "sourceColumn": "[Ano-Campeonato]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "e37ced23-f267-4f11-8f0f-59626d48e161",
        "partitions": [
          {
            "name": "dCalendar",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "VAR MinDataNascimento = ",
                "    CALCULATE(",
                "        MIN(dim_jogadores[Dt Nascimento]),",
                "        NOT(ISBLANK(dim_jogadores[Dt Nascimento]))",
                "    )",
                "RETURN",
                "ADDCOLUMNS(",
                "    CALENDAR(MinDataNascimento, TODAY()),",
                "    \"Ano\", YEAR([Date]),",
                "    \"Mês\", MONTH([Date]),",
                "    \"NomeMês\", FORMAT([Date], \"MMMM\"),",
                "    \"Trimestre\", \"T\" & FORMAT([Date], \"Q\"),",
                "    \"Dia\", DAY([Date]),",
                "    \"Nome do Dia\", FORMAT([Date], \"dddd\"),",
                "    \"Ano-Campeonato\", ",
                "        VAR AnoData = YEAR([Date])",
                "        VAR MesData = MONTH([Date])",
                "        RETURN ",
                "            IF(",
                "                AnoData = 2021 && MesData <= 3, ",
                "                2020, ",
                "                AnoData",
                "            )",
                ")",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dAno",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "6dcb3cac74cf45baa76054a997842210"
          }
        ],
        "columns": [
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "0c45b3fe-3bef-4263-89d6-fbad19f951b5",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "27bcc12f-7130-432f-8547-f738d5852de6",
        "partitions": [
          {
            "name": "dAno",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "    GENERATESERIES(2003, 2023, 1)",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Param_Estatistica",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "3572fb447f164050a1dcf0822cc610d2"
          }
        ],
        "columns": [
          {
            "name": "Parâmetro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "ae3ccc9d-1865-4171-bbfb-e1656d4b8ebf",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Parâmetro Campos"
                }
              ]
            },
            "sortByColumn": "Parâmetro Pedido",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parâmetro Campos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "94ebfbb7-bf43-49e4-a0b5-0b7e0bd8168e",
            "sortByColumn": "Parâmetro Pedido",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parâmetro Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "b495d8c2-7952-48b4-9ee1-037e5006e2b6",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "ba276148-95a0-405a-bf26-03f37a1ad10e",
        "measures": [
          {
            "name": "Card_Desempenho",
            "expression": [
              "",
              "VAR Total = [_jogos]",
              "VAR V = [_vitorias]",
              "VAR E = [_empates]",
              "VAR D = [_derrotas]",
              "",
              "VAR PctV = DIVIDE(V, Total, 0)",
              "VAR PctE = DIVIDE(E, Total, 0)",
              "VAR PctD = DIVIDE(D, Total, 0)",
              "",
              "VAR AnoSelecionado = SELECTEDVALUE(dCalendar[Ano-Campeonato], \"Ano não selecionado\")",
              "",
              "RETURN",
              "\"",
              "<div style='width: 408px; height: 288px; background-color: #1a1a1a; padding: 20px; border-radius: 12px; font-family: Arial, sans-serif; color: white; font-size: 14px; box-shadow: 0 2px 8px rgba(0,0,0,0.4); display: flex; flex-direction: column; justify-content: space-between; gap: 16px;'>",
              "",
              "    <div style='text-align: center; font-size: 18px; font-weight: bold; margin-bottom: 16px;'>",
              "        Brasileirão - \" & AnoSelecionado & \"",
              "    </div>",
              "",
              "    <div>",
              "        <div style='margin-bottom: 4px;'>🟢 <strong>\" & V & \" Vitórias</strong> — \" & FORMAT(PctV, \"0.0%\") & \"</div>",
              "        <div style='height: 12px; background-color: #333; border-radius: 6px; overflow: hidden;'>",
              "            <div style='height: 100%; width: \" & FORMAT(PctV * 100, \"0\") & \"%; background-color: #2ecc71; transition: width 1s ease-in-out;'></div>",
              "        </div>",
              "    </div>",
              "",
              "    <div>",
              "        <div style='margin-bottom: 4px;'>🟡 <strong>\" & E & \" Empates</strong> — \" & FORMAT(PctE, \"0.0%\") & \"</div>",
              "        <div style='height: 12px; background-color: #333; border-radius: 6px; overflow: hidden;'>",
              "            <div style='height: 100%; width: \" & FORMAT(PctE * 100, \"0\") & \"%; background-color: #f1c40f; transition: width 1s ease-in-out;'></div>",
              "        </div>",
              "    </div>",
              "",
              "    <div>",
              "        <div style='margin-bottom: 4px;'>🔴 <strong>\" & D & \" Derrotas</strong> — \" & FORMAT(PctD, \"0.0%\") & \"</div>",
              "        <div style='height: 12px; background-color: #333; border-radius: 6px; overflow: hidden;'>",
              "            <div style='height: 100%; width: \" & FORMAT(PctD * 100, \"0\") & \"%; background-color: #e74c3c; transition: width 1s ease-in-out;'></div>",
              "        </div>",
              "    </div>",
              "",
              "</div>",
              "\"",
              ""
            ],
            "lineageTag": "c491fe47-97ff-4d52-921a-79ca7c45ce07"
          },
          {
            "name": "Card_Vazio",
            "expression": [
              "",
              "\"<html>",
              "<head>",
              "    <meta charset=\"\"UTF-8\"\">",
              "    <meta name=\"\"viewport\"\" content=\"\"width=device-width, initial-scale=1.0\"\">",
              "    <title>Card Vazio</title>",
              "    <style>",
              "        /* ===== VARIÁVEIS GLOBAIS ===== */",
              "        :root {",
              "            --cor-fundo: linear-gradient(45deg, #1a1a1a, #4a4a4a);",
              "            --cor-borda: rgba(255, 255, 255, 0.1);",
              "            --cor-sombra: rgba(0, 0, 0, 0.1);",
              "            --card-largura: 300px;",
              "            --card-altura: 150px;",
              "            --card-padding: 2rem;",
              "            --card-borda-raio: 20px;",
              "        }",
              "",
              "        /* ===== ESTILOS BASE ===== */",
              "        * {",
              "            margin: 0;",
              "            padding: 0;",
              "            box-sizing: border-box;",
              "        }",
              "",
              "        body {",
              "            min-height: 100vh;",
              "            display: flex;",
              "            justify-content: center;",
              "            align-items: center;",
              "            font-family: 'Segoe UI', sans-serif;",
              "        }",
              "",
              "        /* ===== COMPONENTE CARD ===== */",
              "        .kpi-card {",
              "            background: rgba(255, 255, 255, 0.1);",
              "            backdrop-filter: blur(10px);",
              "            border-radius: var(--card-borda-raio);",
              "            padding: var(--card-padding);",
              "            width: var(--card-largura);",
              "            height: var(--card-altura);",
              "            color: white;",
              "            position: relative;",
              "            overflow: hidden;",
              "            box-shadow: 0 8px 32px var(--cor-sombra);",
              "            border: 1px solid var(--cor-borda);",
              "        }",
              "    </style>",
              "</head>",
              "<body>",
              "    <div class=\"\"kpi-card\"\"></div>",
              "</body>",
              "</html>\"",
              ""
            ],
            "lineageTag": "fceb08f1-c0b1-4f9d-9bc7-3783d693d911"
          },
          {
            "name": "Card_vazio2",
            "expression": "\"\"",
            "lineageTag": "6a23b4f9-8c1d-4b1d-919e-a481b19d4270"
          },
          {
            "name": "Card_Desempenho2",
            "expression": [
              "",
              "VAR Total = [_jogos]",
              "VAR V = [_vitorias]",
              "VAR E = [_empates]",
              "VAR D = [_derrotas]",
              "",
              "VAR PctV = DIVIDE(V, Total, 0)",
              "VAR PctE = DIVIDE(E, Total, 0)",
              "VAR PctD = DIVIDE(D, Total, 0)",
              "",
              "VAR AnoSelecionado = SELECTEDVALUE(dCalendar[Ano-Campeonato], \"Ano não selecionado\")",
              "",
              "VAR _cores = IF(",
              "    NOT(ISBLANK(CALCULATE(",
              "        SELECTEDVALUE(dim_cores[Código Hexadecimal]), ",
              "        FILTER(",
              "            dim_cores, ",
              "            dim_cores[Cor] = SELECTEDVALUE(dim_clubes[Cores])",
              "        )",
              "    ))),",
              "    CALCULATE(",
              "        SELECTEDVALUE(dim_cores[Código Hexadecimal]), ",
              "        FILTER(",
              "            dim_cores, ",
              "            dim_cores[Cor] = SELECTEDVALUE(dim_clubes[Cores])",
              "        )",
              "    ),",
              "    \"#000000\"  -- Cor padrão cinza caso não haja cor válida",
              ")",
              "",
              "RETURN",
              "\"",
              "<div style='width: 408px; height: 288px; background-color: \" & _cores & \"; padding: 20px; border-radius: 12px; font-family: Arial, sans-serif; color: white; font-size: 14px; box-shadow: 0 2px 8px rgba(0,0,0,0.4); display: flex; flex-direction: column; justify-content: space-between; gap: 16px;'>",
              "",
              "    <div style='text-align: center; font-size: 18px; font-weight: bold; margin-bottom: 16px;'>",
              "        Brasileirão - \" & AnoSelecionado & \"",
              "    </div>",
              "",
              "    <div>",
              "        <div style='margin-bottom: 4px;'><strong>\" & V & \" Vitórias</strong> — \" & FORMAT(PctV, \"0.0%\") & \"</div>",
              "        <div style='height: 12px; background-color: #e0e0e0; border-radius: 6px; overflow: hidden;'>",
              "            <div style='height: 100%; width: \" & FORMAT(PctV * 100, \"0\") & \"%; background-color: #ffffff; transition: width 1s ease-in-out;'></div>",
              "        </div>",
              "    </div>",
              "",
              "    <div>",
              "        <div style='margin-bottom: 4px;'><strong>\" & E & \" Empates</strong> — \" & FORMAT(PctE, \"0.0%\") & \"</div>",
              "        <div style='height: 12px; background-color: #e0e0e0; border-radius: 6px; overflow: hidden;'>",
              "            <div style='height: 100%; width: \" & FORMAT(PctE * 100, \"0\") & \"%; background-color: #ffffff; transition: width 1s ease-in-out;'></div>",
              "        </div>",
              "    </div>",
              "",
              "    <div>",
              "        <div style='margin-bottom: 4px;'><strong>\" & D & \" Derrotas</strong> — \" & FORMAT(PctD, \"0.0%\") & \"</div>",
              "        <div style='height: 12px; background-color: #e0e0e0; border-radius: 6px; overflow: hidden;'>",
              "            <div style='height: 100%; width: \" & FORMAT(PctD * 100, \"0\") & \"%; background-color: #ffffff; transition: width 1s ease-in-out;'></div>",
              "        </div>",
              "    </div>",
              "",
              "</div>",
              "\"",
              ""
            ],
            "lineageTag": "3201cabb-b9f6-4a4e-aeb7-2976cb777317"
          }
        ],
        "partitions": [
          {
            "name": "Param_Estatistica",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Pontuação\", NAMEOF([_pontosAno]), 0),",
                "    (\"Classificação\", NAMEOF([_PosicaoMaximaAno]), 1),",
                "    (\"Gols Pro\", NAMEOF([_golsProAno]), 2),",
                "    (\"Gols Contra\", NAMEOF([_golsContraAno]), 3),",
                "    (\"Saldo de Gols\", NAMEOF([_golsSGAno]), 4)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dim_cores",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Índice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "825fb12f-7d0f-4698-8fea-41b2e0c473db",
            "sourceColumn": "Índice",
            "summarizeBy": "none"
          },
          {
            "name": "Cor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b3b4cc98-cdcc-4c79-8ee8-fa1b02f9cfe1",
            "sourceColumn": "Cor",
            "summarizeBy": "none"
          },
          {
            "name": "Código Hexadecimal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "24629a4b-c774-487f-ad0f-88abe51e79d2",
            "sourceColumn": "Código Hexadecimal",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "930cc5ec-6408-47dc-b0a8-25cd5b35fa6d",
        "partitions": [
          {
            "name": "dim_cores",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"dZI9EsIgEIWvksE2BRuCklI01lY2GQtURov4M4xaeBvP4sUkQXDBOFSwH28fb2kaAiQnK212OtPZxqjT9mwPRiAnvJRknTekcMBRt4dzxNS0tKtnWMxcjL6mCLf76ePWRhKF5FAt+vr4U8+z+1AzRE4C6cqWU0dldJuCogNdJTa+qCnwHqnsftm5HRaTQoypiwEoCgohKCkIWSK1vdGn1zMlcah5ptJcUG7AwnP7WP+lAmUk+ctiTf41Opg2ttoNRvrXhMmyms3Z3BF+IKkjEW5GbQY1Kv89tq0ysRnKBcyc8YL6eUWEF1q/AQ==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Índice = _t, Cor = _t, #\"Código Hexadecimal\" = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Índice\", Int64.Type}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}