createOrReplace

	ref table Medidas

		measure RadarMandante =
				CALCULATE(
				    MAX(dim_clubes[clube]),
				    FILTER(
				        'full - unpivot',
				        'full - unpivot'[mandante_flag] = "S"
				    ),
				    TREATAS(
				        VALUES('campeonato-brasileiro-estatisticas-full'[id_time]),
				        'full - unpivot'[id_time]
				    ),
				    TREATAS(
				        VALUES('campeonato-brasileiro-estatisticas-full'[rodata]),
				        'full - unpivot'[rodata]
				    ),
				    USERELATIONSHIP('full - unpivot'[id_time], 'campeonato-brasileiro-estatisticas-full'[id_time])
				)
			displayFolder: Partidas\Partida
			lineageTag: 9aa18d7d-dc24-4e81-a37a-774283bf31f0

