createOrReplace

	ref table Medidas

		measure Precisao_Mandante = ```
				
				VAR _precisao = 
				    CALCULATE(
				        MAX('campeonato-brasileiro-estatisticas-full'[precisao_passes]),
				        FILTER('full - unpivot','full - unpivot'[id_time] =  CALCULATE(MIN('campeonato-brasileiro-estatisticas-full'[id_time]), 'full - unpivot'[mandante_flag] = "S")
				        
				    )
				)
				
				RETURN
				COALESCE(FORMAT(_precisao, "0%"), "-")
				```
			displayFolder: Partidas\Estatisticas\Mandante
			lineageTag: 685c4b97-59e3-4034-94dd-5dbbeb3815c0

			changedProperty = IsHidden

		measure Posse_Mandante = ```
				
				VAR _posse = 
				    CALCULATE(
				        MAX('campeonato-brasileiro-estatisticas-full'[posse_de_bola]),
				        FILTER('full - unpivot','full - unpivot'[id_time] =  CALCULATE(MIN('campeonato-brasileiro-estatisticas-full'[id_time]), 'full - unpivot'[mandante_flag] = "S")
				        
				    )
				)
				
				RETURN
				COALESCE(FORMAT(_posse, "0%"), "-")
				```
			displayFolder: Partidas\Estatisticas\Mandante
			lineageTag: f756df44-f123-4445-b275-48571aaec8ad

			changedProperty = IsHidden

		measure Passes_Mandante = ```
				
				VAR _passes = 
				    CALCULATE(
				        MAX('campeonato-brasileiro-estatisticas-full'[passes]),
				        FILTER('full - unpivot','full - unpivot'[id_time] =  CALCULATE(MIN('campeonato-brasileiro-estatisticas-full'[id_time]), 'full - unpivot'[mandante_flag] = "S")
				        
				    )
				)
				
				RETURN
				COALESCE(_passes, "-")
				```
			formatString: 0
			displayFolder: Partidas\Estatisticas\Mandante
			lineageTag: 6bcb4db6-3bc0-4cc3-8017-f7e674bcb18b

			changedProperty = IsHidden

		measure Impedimentos_Mandante = ```
				
				VAR _impedimentos = 
				    CALCULATE(
				        MAX('campeonato-brasileiro-estatisticas-full'[impedimentos]),
				        FILTER('full - unpivot','full - unpivot'[id_time] =  CALCULATE(MIN('campeonato-brasileiro-estatisticas-full'[id_time]), 'full - unpivot'[mandante_flag] = "S")
				        
				    )
				)
				
				RETURN
				COALESCE(_impedimentos, "-")
				```
			formatString: 0
			displayFolder: Partidas\Estatisticas\Mandante
			lineageTag: 5f95d6a1-008c-40e3-b8c4-792df7f77902

			changedProperty = IsHidden

		measure Finalizacoes_Mandante = ```
				
				VAR _chutes = 
				    CALCULATE(
				        MAX('campeonato-brasileiro-estatisticas-full'[chutes_no_alvo]),
				        FILTER('full - unpivot','full - unpivot'[id_time] =  CALCULATE(MIN('campeonato-brasileiro-estatisticas-full'[id_time]), 'full - unpivot'[mandante_flag] = "S")
				        
				    )
				)
				
				RETURN
				COALESCE(_chutes, 0)
				```
			formatString: 0
			displayFolder: Partidas\Estatisticas\Mandante
			lineageTag: 15e07458-23d5-41a0-a7a6-b519a44475cf

			changedProperty = IsHidden

		measure Faltas_Mandante = ```
				
				VAR _faltas = 
				    CALCULATE(
				        MAX('campeonato-brasileiro-estatisticas-full'[faltas]),
				        FILTER('full - unpivot','full - unpivot'[id_time] =  CALCULATE(MIN('campeonato-brasileiro-estatisticas-full'[id_time]), 'full - unpivot'[mandante_flag] = "S")
				        
				    )
				)
				
				RETURN
				COALESCE(_faltas, "-")
				```
			formatString: 0
			displayFolder: Partidas\Estatisticas\Mandante
			lineageTag: 8d7464b8-3e81-4d64-ba92-38a41979bd6f

			changedProperty = IsHidden

		measure Escanteios_Mandante = ```
				
				VAR _escanteios = 
				    CALCULATE(
				        MAX('campeonato-brasileiro-estatisticas-full'[escanteios]),
				        FILTER('full - unpivot','full - unpivot'[id_time] =  CALCULATE(MIN('campeonato-brasileiro-estatisticas-full'[id_time]), 'full - unpivot'[mandante_flag] = "S")
				        
				    )
				)
				
				RETURN
				COALESCE(_escanteios, "-")
				```
			formatString: 0
			displayFolder: Partidas\Estatisticas\Mandante
			lineageTag: b6824c67-a31f-44d0-ab99-4d9e5b72ba2e

			changedProperty = IsHidden

		measure Chutes_Mandante = ```
				
				VAR _chutes = 
				    CALCULATE(
				        MAX('campeonato-brasileiro-estatisticas-full'[chutes]),
				        FILTER('full - unpivot','full - unpivot'[id_time] =  CALCULATE(MIN('campeonato-brasileiro-estatisticas-full'[id_time]), 'full - unpivot'[mandante_flag] = "s")
				        
				    )
				)
				
				RETURN
				COALESCE(_chutes, 0)
				```
			formatString: 0
			displayFolder: Partidas\Estatisticas\Mandante
			lineageTag: d372a25d-ce36-4e7e-a8b4-f90cd234cc2d

			changedProperty = IsHidden

		measure CartoesVermelho_Mandante = ```
				
				VAR _cartoes = 
				    CALCULATE(
				        MAX('campeonato-brasileiro-estatisticas-full'[cartao_vermelho]),
				        FILTER('full - unpivot','full - unpivot'[id_time] =  CALCULATE(MIN('campeonato-brasileiro-estatisticas-full'[id_time]), 'full - unpivot'[mandante_flag] = "S")
				        
				    )
				)
				
				RETURN
				COALESCE(_cartoes, "-")
				```
			formatString: 0
			displayFolder: Partidas\Estatisticas\Mandante
			lineageTag: fbcd940e-2c5d-4e53-9e0c-0c69ddb2e3f5

			changedProperty = IsHidden

		measure CartoesAmarelo_Mandante = ```
				
				VAR _cartoes = 
				    CALCULATE(
				        MAX('campeonato-brasileiro-estatisticas-full'[cartao_amarelo]),
				        FILTER('full - unpivot','full - unpivot'[id_time] =  CALCULATE(MIN('campeonato-brasileiro-estatisticas-full'[id_time]), 'full - unpivot'[mandante_flag] = "S")
				        
				    )
				)
				
				RETURN
				COALESCE(_cartoes, "-")
				```
			formatString: 0
			displayFolder: Partidas\Estatisticas\Mandante
			lineageTag: cfc9e905-9218-4b3f-a155-6d64ce76a52c

			changedProperty = IsHidden

