table fct_gols_jogador
	lineageTag: f83b88c4-57fe-43c6-9053-6a359a4eef88

	measure ListaJogadoresOrdenadaPorGols = ```
			
			VAR JogadoresComGols =
			    ADDCOLUMNS(
			        VALUES('fct_gols_jogador'[atleta]),
			        "Gols", sum(fct_gols_jogador[TotalGols])
			    )
			RETURN
			    CONCATENATEX(
			        FILTER(JogadoresComGols, [Gols] > 0),
			        'fct_gols_jogador'[atleta],
			        ", ",
			        [Gols],
			        DESC
			    )
			
			```
		lineageTag: 2476f4cd-0007-4ef5-bffb-499e6a467e0a

	measure filtro = if(ISBLANK(SELECTEDVALUE(dAno[Ano])),false, TRUE())
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 68475643-05c7-463f-89dd-90d638e1f54b

	column Ano
		formatString: 0
		lineageTag: 736f08b6-7566-401d-9f66-d5e126d5c9b0
		summarizeBy: none
		isNameInferred
		sourceColumn: [Ano]

		annotation SummarizationSetBy = Automatic

	column TotalGols
		formatString: 0
		lineageTag: a5d7aff6-605f-4454-bbbf-8f1a32c8278d
		summarizeBy: sum
		isNameInferred
		sourceColumn: [TotalGols]

		annotation SummarizationSetBy = Automatic

	column Imagem
		lineageTag: 9f2d45df-c073-41ef-866a-2d4c5e1b63f0
		summarizeBy: none
		isNameInferred
		sourceColumn: [Imagem]

		annotation SummarizationSetBy = Automatic

	column Nascimento
		formatString: General Date
		lineageTag: 85176d19-7fb0-414f-9991-005beab331e3
		summarizeBy: none
		isNameInferred
		sourceColumn: [Nascimento]

		variation Variation
			isDefault
			relationship: 4fef5f43-4488-4c7d-bf78-e97d6533d9c2
			defaultHierarchy: LocalDateTable_70fc6a57-934d-491c-922b-da12b4e2d60f.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Nacionalidade
		lineageTag: 6951fe41-6bbd-48b9-b358-02a66ec25343
		summarizeBy: none
		isNameInferred
		sourceColumn: [Nacionalidade]

		annotation SummarizationSetBy = Automatic

	column Posição
		lineageTag: 61c13709-c4b7-4cf9-b3fc-5638eba56e87
		summarizeBy: none
		isNameInferred
		sourceColumn: [Posição]

		annotation SummarizationSetBy = Automatic

	column Situação
		lineageTag: ccaf3a4c-95c9-46a9-9dc9-436c5dba0585
		summarizeBy: none
		isNameInferred
		sourceColumn: [Situação]

		annotation SummarizationSetBy = Automatic

	column ClubeAtual
		lineageTag: b556369d-f7e6-49a5-bcd4-cea958cbbc4d
		summarizeBy: none
		isNameInferred
		sourceColumn: [ClubeAtual]

		annotation SummarizationSetBy = Automatic

	column Apelido
		lineageTag: 40ac1190-b565-421f-bc93-2b8b86cc677b
		summarizeBy: none
		isNameInferred
		sourceColumn: [Apelido]

		annotation SummarizationSetBy = Automatic

	column Time
		lineageTag: 522205c5-b9dc-4e20-8863-a2e1b1839979
		summarizeBy: none
		isNameInferred
		sourceColumn: [Time]

		annotation SummarizationSetBy = Automatic

	column Atleta
		lineageTag: 6bcb1f23-4d6b-410b-a0a1-bd3739f2bf21
		summarizeBy: none
		isNameInferred
		sourceColumn: [Atleta]

		annotation SummarizationSetBy = Automatic

	column TotalGolsPorAtleta = ```
			
			CALCULATE(
			    SUM(fct_gols_jogador[TotalGols]),
			    ALLEXCEPT(fct_gols_jogador, fct_gols_jogador[atleta])
			)
			
			```
		formatString: 0
		lineageTag: 34b80bdf-7924-4da2-a5f8-7750a10fe37b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column TotalGolsPorAtletaAno = ```
			
			CALCULATE(
			    SUM(fct_gols_jogador[TotalGols]),
			    ALLEXCEPT(fct_gols_jogador, fct_gols_jogador[atleta], fct_gols_jogador[Ano])
			)
			
			```
		formatString: 0
		lineageTag: 66ba3709-818a-4f3a-81be-cf50fd8b1e7f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column orderatletas = if([filtro] = FALSE(), fct_gols_jogador[TotalGolsPorAtletaAno], fct_gols_jogador[TotalGolsPorAtleta])
		formatString: 0
		lineageTag: 3f1d556c-5626-408f-842e-3e50a833817e
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition fct_gols_jogador = calculated
		mode: import
		source = ```
				
				VAR Base =
				    SELECTCOLUMNS(
				        'campeonato-brasileiro-gols',
				        "Atleta", 'campeonato-brasileiro-gols'[atleta],
				        "PartidaID", 'campeonato-brasileiro-gols'[partida_id],
				        "Time", LOOKUPVALUE(
				            'full - unpivot'[time],
				            'full - unpivot'[id_time],
				            'campeonato-brasileiro-gols'[id_time]
				        ),
				        "Ano", LOOKUPVALUE(
				            'dCalendar'[Ano-Campeonato],
				            'dCalendar'[Date],
				            LOOKUPVALUE(
				                'full - unpivot'[data],
				                'full - unpivot'[id_time],
				                'campeonato-brasileiro-gols'[id_time]
				            )
				        )
				    )
				VAR TabelaCompleta =
				    ADDCOLUMNS(
				        SUMMARIZE(
				            Base,
				            [Atleta],
				            [Time],
				            [Ano]
				        ),
				        "TotalGols", COUNTROWS(
				            FILTER(Base, 
				                [Atleta] = EARLIER([Atleta]) &&
				                [Time] = EARLIER([Time]) &&
				                [Ano] = EARLIER([Ano])
				            )
				        ),
				        "Imagem", LOOKUPVALUE('dim_jogadores'[imagem], 'dim_jogadores'[atleta], [Atleta]),
				        "Nascimento", LOOKUPVALUE('dim_jogadores'[dt nascimento], 'dim_jogadores'[atleta], [Atleta]),
				        "Nacionalidade", LOOKUPVALUE('dim_jogadores'[nacionalidade], 'dim_jogadores'[atleta], [Atleta]),
				        "Posição", LOOKUPVALUE('dim_jogadores'[posição], 'dim_jogadores'[atleta], [Atleta]),
				        "Situação", LOOKUPVALUE('dim_jogadores'[situação], 'dim_jogadores'[atleta], [Atleta]),
				        "ClubeAtual", LOOKUPVALUE('dim_jogadores'[clube atual], 'dim_jogadores'[atleta], [Atleta]),
				        "Apelido", LOOKUPVALUE('dim_jogadores'[_apelido], 'dim_jogadores'[atleta], [Atleta])
				    )
				RETURN
				    FILTER(
				        TabelaCompleta,
				        NOT ISBLANK([Imagem]) && [Imagem] <> ""
				    )
				
				```

	annotation PBI_Id = 97c686a543da4938bba3ef22f59af79a

