table dim_clubes
	lineageTag: 56adcef3-ffc6-4210-ba8e-c9f949acac9c

	column Clube
		dataType: string
		lineageTag: c67efa65-75cf-4bfe-948b-acbb385dd18d
		summarizeBy: none
		sourceColumn: Clube

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Fundacao
		dataType: string
		lineageTag: a64cc4e3-d015-4b94-9723-ec3cd835b0b3
		summarizeBy: none
		sourceColumn: Fundacao

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Mascote
		dataType: string
		lineageTag: 80299c1b-f7b9-44b0-997b-07b5e912c466
		summarizeBy: none
		sourceColumn: Mascote

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Estadio
		dataType: string
		lineageTag: f0780a50-d2d2-4a15-9b9f-8d720e02d151
		summarizeBy: none
		sourceColumn: Estadio

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Cores
		dataType: string
		lineageTag: 465f7a19-c847-415e-9c4e-828380ce5d65
		summarizeBy: none
		sourceColumn: Cores

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Apelido
		dataType: string
		lineageTag: df41b987-f85d-4253-a80e-289e34545b5d
		summarizeBy: none
		sourceColumn: Apelido

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Clube_s_acentos
		dataType: string
		lineageTag: c90f949c-d573-4d03-8112-8c39f2d69e89
		summarizeBy: none
		sourceColumn: Clube_s_acentos

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Url
		dataType: string
		lineageTag: a0bc7821-4615-4658-9b71-228fb4e3c14d
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: Url
		sortByColumn: id

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column id
		dataType: int64
		formatString: 0
		lineageTag: 49b7da18-fcbe-418e-864a-e7a932dc00a0
		summarizeBy: sum
		sourceColumn: id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Cidade
		dataType: string
		lineageTag: 5b70cc9e-75b8-432c-9910-183004e026ed
		dataCategory: City
		summarizeBy: none
		sourceColumn: Cidade

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: 33052850-d2fb-4c9b-ade4-4f8ada12b24c
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: Estado

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Bio
		dataType: string
		lineageTag: a85ed081-12a5-4b48-858f-0290eb972d8a
		summarizeBy: none
		sourceColumn: Bio

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition dim_clubes = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\MSI\Documents\PBI\Brasileirao\07-Brasileirao\clubes.xlsx"), null, true),
				    Planilha2_Sheet = Fonte{[Item="Planilha2",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Planilha2_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Clube", type text}, {"Fundacao", type text}, {"Mascote", type text}, {"Estadio", type text}, {"Cores", type text}, {"Apelido", type text}, {"id", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

