table dim_jogadores
	lineageTag: 33aeea26-f2b9-49e3-b904-0f873a42d10d

	column atleta
		dataType: string
		lineageTag: 9073d774-102c-4868-a9d4-47daaf487170
		summarizeBy: none
		sourceColumn: atleta

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Imagem
		dataType: string
		lineageTag: 491eb021-c823-48db-b409-077e532542a8
		summarizeBy: none
		sourceColumn: Imagem

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Dt Nascimento'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0015dbc2-50a8-4dfa-bf92-0d36175a7eca
		summarizeBy: none
		sourceColumn: Dt Nascimento

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Local Nascimento'
		dataType: string
		lineageTag: 885d01b3-c9b6-463a-a566-c539fa06eacc
		summarizeBy: none
		sourceColumn: Local Nascimento

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Nacionalidade
		dataType: string
		lineageTag: 9a23b68c-f979-4f35-bcdb-26fd58adfacb
		summarizeBy: none
		sourceColumn: Nacionalidade

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Posição
		dataType: string
		lineageTag: f0b4f8d7-d951-45ec-99e2-daf96bc2fd01
		summarizeBy: none
		sourceColumn: Posição

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Situação
		dataType: string
		lineageTag: a17182c5-3120-41ae-a453-e3569108cb65
		summarizeBy: none
		sourceColumn: Situação

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Clube Atual'
		dataType: string
		lineageTag: cde7d4af-5482-43d1-870c-fd4cf2db6d50
		summarizeBy: none
		sourceColumn: Clube Atual

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Biografia
		dataType: string
		lineageTag: d8434654-5bc0-4cad-b03c-9ff435e8afae
		summarizeBy: none
		sourceColumn: Biografia

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Pé-Preferencial
		dataType: string
		lineageTag: 27dbbcd6-3d7f-4dd1-bbb8-c3b9685b5cf4
		summarizeBy: none
		sourceColumn: Pé-Preferencial

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Nome
		dataType: string
		lineageTag: 7f00dde3-38e5-4d14-aa17-a7e35e5ea9d9
		summarizeBy: none
		sourceColumn: Nome

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column _apelido = ```
			
			VAR PalavrasApelido = SUBSTITUTE(LOWER(dim_jogadores[atleta]), " ", "|")
			VAR PalavrasNome = SUBSTITUTE(LOWER(dim_jogadores[Nome]), " ", "|")
			
			VAR ListaApelido =
			    ADDCOLUMNS(
			        GENERATESERIES(1, PATHLENGTH(PalavrasApelido)),
			        "Palavra", PATHITEM(PalavrasApelido, [Value])
			    )
			
			-- Verifica se todas as palavras do apelido estão presentes no nome
			VAR TodasPalavrasPresentes =
			    COUNTROWS(
			        FILTER(
			            ListaApelido,
			            NOT PATHCONTAINS(PalavrasNome, [Palavra])
			        )
			    ) = 0
			
			-- Só mostra o apelido se NÃO estiver contido no nome completo
			VAR MostrarApelido =
			    NOT ISBLANK(dim_jogadores[Imagem]) &&
			    NOT TodasPalavrasPresentes &&
			    LEN(dim_jogadores[atleta]) < LEN(dim_jogadores[Nome])
			
			VAR ApelidoFinal = 
			    IF(MostrarApelido, dim_jogadores[atleta], BLANK())
			
			RETURN
			IF(
			    NOT ISBLANK(ApelidoFinal),
			    dim_jogadores[Nome] & " (" & ApelidoFinal & ")",
			    dim_jogadores[Nome]
			)
			
			```
		lineageTag: 51064e85-c414-4437-9b22-1dc8c0595234
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition dim_jogadores = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\MSI\Documents\PBI\Brasileirao\jogadores.xlsx"), null, true),
				    campeonato_brasileiro_gols_Table = Fonte{[Item="campeonato_brasileiro_gols",Kind="Table"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(campeonato_brasileiro_gols_Table,{{"clube", type text}, {"atleta", type text}, {"Imagem", type text}, {"Dt Nascimento", type date}, {"Local Nascimento", type text}, {"Nacionalidade", type text}, {"Posição", type text}, {"Pé-Preferencial", type text}, {"Situação", type text}, {"Clube Atual", type text}, {"Biografia", type text}}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Tipo Alterado", {"atleta"}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Duplicatas Removidas",{"clube"}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Colunas Removidas", each [atleta] <> null and [atleta] <> "")
				in
				    #"Linhas Filtradas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

