table dim_clubes
	lineageTag: 56adcef3-ffc6-4210-ba8e-c9f949acac9c

	column Clube
		dataType: string
		lineageTag: c67efa65-75cf-4bfe-948b-acbb385dd18d
		summarizeBy: none
		sourceColumn: Clube

		annotation SummarizationSetBy = Automatic

	column Fundacao
		dataType: dateTime
		formatString: Long Date
		lineageTag: a64cc4e3-d015-4b94-9723-ec3cd835b0b3
		summarizeBy: none
		sourceColumn: Fundacao

		variation Variation
			isDefault
			relationship: 266e4fa8-1fc9-4be9-b247-e3d996aa4ef8
			defaultHierarchy: LocalDateTable_2ea599c2-7a12-48e5-845a-02093c9b8bcd.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Mascote
		dataType: string
		lineageTag: 80299c1b-f7b9-44b0-997b-07b5e912c466
		summarizeBy: none
		sourceColumn: Mascote

		annotation SummarizationSetBy = Automatic

	column Estadio
		dataType: string
		lineageTag: f0780a50-d2d2-4a15-9b9f-8d720e02d151
		summarizeBy: none
		sourceColumn: Estadio

		annotation SummarizationSetBy = Automatic

	column Cores
		dataType: string
		lineageTag: 465f7a19-c847-415e-9c4e-828380ce5d65
		summarizeBy: none
		sourceColumn: Cores

		annotation SummarizationSetBy = Automatic

	column Apelido
		dataType: string
		lineageTag: df41b987-f85d-4253-a80e-289e34545b5d
		summarizeBy: none
		sourceColumn: Apelido

		annotation SummarizationSetBy = Automatic

	column Clube_s_acentos
		dataType: string
		lineageTag: c90f949c-d573-4d03-8112-8c39f2d69e89
		summarizeBy: none
		sourceColumn: Clube_s_acentos

		annotation SummarizationSetBy = Automatic

	column Url
		dataType: string
		lineageTag: a0bc7821-4615-4658-9b71-228fb4e3c14d
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: Url
		sortByColumn: id

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column id
		dataType: int64
		formatString: 0
		lineageTag: 49b7da18-fcbe-418e-864a-e7a932dc00a0
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column bg = RELATED(Tabela[Coluna 2])
		lineageTag: d531195d-512e-4fc5-a352-78722c398019
		dataCategory: ImageUrl
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Cidade
		dataType: string
		lineageTag: 5b70cc9e-75b8-432c-9910-183004e026ed
		dataCategory: City
		summarizeBy: none
		sourceColumn: Cidade

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: 33052850-d2fb-4c9b-ade4-4f8ada12b24c
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	partition dim_clubes = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\MSI\Documents\PBI\Brasileirao\07-Brasileirao\clubes.xlsx"), null, true),
				    Planilha2_Sheet = Fonte{[Item="Planilha2",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Planilha2_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Clube", type text}, {"Fundacao", type date}, {"Mascote", type text}, {"Estadio", type text}, {"Cores", type text}, {"Apelido", type text}, {"id", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

