table dim_cores
	lineageTag: 930cc5ec-6408-47dc-b0a8-25cd5b35fa6d

	column Índice
		dataType: int64
		formatString: 0
		lineageTag: 825fb12f-7d0f-4698-8fea-41b2e0c473db
		summarizeBy: none
		sourceColumn: Índice

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Cor
		dataType: string
		lineageTag: b3b4cc98-cdcc-4c79-8ee8-fa1b02f9cfe1
		summarizeBy: none
		sourceColumn: Cor

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Código Hexadecimal'
		dataType: string
		lineageTag: 24629a4b-c774-487f-ad0f-88abe51e79d2
		summarizeBy: none
		sourceColumn: Código Hexadecimal

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition dim_cores = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("dZIxEsIgEEWvksE2BRuCJqUxSW1lk0mBymgRjcOohbfxLF5MEgQXjEMF+/j7+UvTECAx2Ui1l5GMtkqcd70+mEGx4GlB2rghiQFOsjv2HlPRVK+RYT5zUfIaIlzvl49b50kkBYe8HuvzTz2O7lPNELlwpClrTpyEkl0IZgNoKr7xuqLARyTX+/XgdloMkUBRUAhBSYHLEqkdlDy/niGJQ40jEeaCcgPmnjvG+i8VSD3JXxZr8q/RybSx1WEwhX2NmyyrWMlKQ9iBhI4yd9NrM6mR2++x64TyzVCewcoYT6idl0dYofYN", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Índice = _t, Cor = _t, #"Código Hexadecimal" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Índice", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

