table dim_formacao
	lineageTag: 104ec447-5fd4-466f-bb52-131e8cd47a5c

	column formacao
		dataType: string
		lineageTag: b2e3463c-23c4-43eb-8816-ad1d7f0b328c
		summarizeBy: none
		sourceColumn: formacao

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column url
		dataType: string
		lineageTag: d22bdbb1-50a0-4163-a1ae-a054552589ce
		summarizeBy: none
		sourceColumn: url

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition dim_formacao = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\MSI\Documents\PBI\Brasileirao\formacao.xlsx"), null, true),
				    Planilha1_Sheet = Fonte{[Item="Planilha1",Kind="Sheet"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(Planilha1_Sheet,{{"Column1", type text}, {"Column2", type text}}),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Tipo Alterado", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"formacao", type text}, {"url", type text}})
				in
				    #"Tipo Alterado1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

