table fato_CBCartoes
	lineageTag: 38b31757-60fd-41af-8ae7-4f9a0b290e9c

	column partida_id
		dataType: int64
		formatString: 0
		lineageTag: 51ac3b8e-202c-4793-b28c-debf99b6f03a
		summarizeBy: sum
		sourceColumn: partida_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column rodata
		dataType: int64
		formatString: 0
		lineageTag: 70d52035-2994-488e-91b8-b00cd86a67f7
		summarizeBy: sum
		sourceColumn: rodata

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column clube
		dataType: string
		lineageTag: 0562273c-c1f2-4a32-9ce5-fb414705a8ca
		summarizeBy: none
		sourceColumn: clube

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column cartao
		dataType: string
		lineageTag: acecaff9-b1a4-4d47-86c1-52e2628e6e06
		summarizeBy: none
		sourceColumn: cartao

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column atleta
		dataType: string
		lineageTag: 6cf16c92-e7fd-494c-ad62-e1ca6f8ac21f
		summarizeBy: none
		sourceColumn: atleta

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column num_camisa
		dataType: int64
		formatString: 0
		lineageTag: a0840383-fc53-41f2-b2a5-648e4faa15ff
		summarizeBy: sum
		sourceColumn: num_camisa

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column posicao
		dataType: string
		lineageTag: 93d352a3-6b87-42f5-8897-cdc04ec8cdc6
		summarizeBy: none
		sourceColumn: posicao

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column minuto
		dataType: int64
		formatString: 0
		lineageTag: f76660b8-6feb-4d8f-a3c3-96ab152364b2
		summarizeBy: sum
		sourceColumn: minuto

		changedProperty = DataType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column id_time
		dataType: string
		lineageTag: 141ac270-33c2-4350-bc4a-08399352da48
		summarizeBy: none
		sourceColumn: id_time

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Faixa Minuto Categoria' = SWITCH(true(), 'fato_CBCartoes'[minuto] <=15, "15", AND('fato_CBCartoes'[minuto] <=30, 'fato_CBCartoes'[minuto] >15), "30", AND('fato_CBCartoes'[minuto] <=45, 'fato_CBCartoes'[minuto] >30), "45", AND('fato_CBCartoes'[minuto] <=60, 'fato_CBCartoes'[minuto] >45), "60", AND('fato_CBCartoes'[minuto] <=75, 'fato_CBCartoes'[minuto] >60), "75", AND('fato_CBCartoes'[minuto] <=90, 'fato_CBCartoes'[minuto] >75), "90", 'fato_CBCartoes'[minuto] >90, "Acréscimos")
		lineageTag: 42f1e1ed-10f3-40bf-a04d-4b2afa7374a4
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition fato_CBCartoes = m
		mode: import
		queryGroup: 'Tabelas Fato'
		source =
				let
				    Fonte = Csv.Document(Web.Contents("https://raw.githubusercontent.com/anapaccasilva/CampeonatoBrasileiro/refs/heads/main/Bases/campeonato-brasileiro-cartoes.csv"),[Delimiter=",", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"partida_id", Int64.Type}, {"rodata", Int64.Type}, {"clube", type text}, {"cartao", type text}, {"atleta", type text}, {"num_camisa", Int64.Type}, {"posicao", type text}, {"minuto", type text}}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Tipo Alterado","Clayson","Clayson Henrique da Silva Vieira",Replacer.ReplaceValue,{"atleta"}),
				    #"Valor Substituído1" = Table.ReplaceValue(#"Valor Substituído","","Everton Kempes dos Santos",Replacer.ReplaceValue,{"atleta"}),
				    #"Valor Substituído2" = Table.ReplaceValue(#"Valor Substituído1","Gabriel Barbosa Almeida","Gabriel Barbosa",Replacer.ReplaceText,{"atleta"}),
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Valor Substituído2", "id_time", each Text.Combine({Text.From([partida_id], "pt-BR"), "_", [clube]}), type text),
				    #"Dividir Coluna por Delimitador" = Table.SplitColumn(#"Coluna Mesclada Inserida", "minuto", Splitter.SplitTextByDelimiter("+", QuoteStyle.Csv), {"minuto.1", "minuto.2"}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Dividir Coluna por Delimitador",{{"minuto.1", Int64.Type}, {"minuto.2", Int64.Type}}),
				    #"Valor Substituído3" = Table.ReplaceValue(#"Tipo Alterado1",null,0,Replacer.ReplaceValue,{"minuto.2"}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Valor Substituído3", "minuto", each [minuto.1]+[minuto.2]),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Personalização Adicionada",{"minuto.1", "minuto.2"})
				in
				    #"Colunas Removidas"

	changedProperty = Name

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

