table fct_classificacao
	lineageTag: 542f90ee-9360-4b32-8af8-77287be71bf2

	measure Medida
		lineageTag: c8c216c6-b9b2-4bfa-b0cc-160a5c9c59c3

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure 'teste_game _' = ```
			
			"<div style='font-family: Arial, sans-serif; padding: 20px; text-align: center;'>
			    <h2>Pergunta: Qual é a capital da França?</h2>
			    <div>
			        <button>Paris</button>
			        <button>Londres</button>
			        <button>Roma</button>
			    </div>
			    <p style='font-size: 18px;'>Sua resposta: " & 
			     
			    "</p>
			</div>"
			
			```
		lineageTag: 36a95905-6d7b-4f33-adc9-870fd480b087

	measure _PosicaoMaximaAno = ```
			
			CALCULATE(
			    MIN(fct_classificacao[Ranking_times]))
			
			```
		formatString: 0
		lineageTag: 8f0b018b-6bd3-499c-bb3f-654b0df0cd89

	measure ranking_emoji = IF(selectedvalue(fct_classificacao[Ranking_times]) = 1, CONCATENATE("🏆", INT(selectedvalue(fct_classificacao[Ranking_times]))), INT(selectedvalue(fct_classificacao[Ranking_times])))
		lineageTag: 766148fa-fdc1-4f4e-a934-2ece85d0f600

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column time
		lineageTag: a8ad2e6d-33e3-4c40-92ae-3af6584a84b9
		summarizeBy: none
		isNameInferred
		sourceColumn: full - unpivot[time]

		annotation SummarizationSetBy = Automatic

	column TotalPontos
		formatString: 0
		lineageTag: 6205ee72-9e4a-42d3-b45a-56bd677066b7
		summarizeBy: sum
		isNameInferred
		sourceColumn: [TotalPontos]

		annotation SummarizationSetBy = Automatic

	column Ranking_times =
			
			VAR AnoAtual = [Ano]
			RETURN
			RANKX(
			    FILTER(
			        fct_classificacao,
			        [Ano] = AnoAtual
			    ),
			     fct_classificacao[TotalPontos] * 1000000 +
			     fct_classificacao[TotalVitorias] * 10000 +
			     fct_classificacao[SaldoGols] * 100 +
			     fct_classificacao[GolsPro],
			    ,
			    DESC,
			    DENSE
			)
		formatString: 0
		lineageTag: 6cc7a3fd-af2c-4595-8c43-fa29368d322c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column TotalVitorias
		formatString: 0
		lineageTag: 7f893e42-1859-45ea-a7dc-7a9895042a15
		summarizeBy: sum
		isNameInferred
		sourceColumn: [TotalVitorias]

		annotation SummarizationSetBy = Automatic

	column SaldoGols
		formatString: 0
		lineageTag: a6e9ed28-7e9f-41bb-859c-d599fa9526f8
		summarizeBy: sum
		isNameInferred
		sourceColumn: [SaldoGols]

		annotation SummarizationSetBy = Automatic

	column TotalJogos
		formatString: 0
		lineageTag: c366fd43-4aba-4ac9-92d6-bcadc973975a
		summarizeBy: sum
		isNameInferred
		sourceColumn: [TotalJogos]

		annotation SummarizationSetBy = Automatic

	column TotalDerrotas
		formatString: 0
		lineageTag: c925ee07-fdc5-4026-99f6-29b2ffddb289
		summarizeBy: sum
		isNameInferred
		sourceColumn: [TotalDerrotas]

		annotation SummarizationSetBy = Automatic

	column TotalEmpates
		formatString: 0
		lineageTag: 1af3fced-06fb-4ed5-99ed-fe8a49dbad6f
		summarizeBy: sum
		isNameInferred
		sourceColumn: [TotalEmpates]

		annotation SummarizationSetBy = Automatic

	column GolsPro
		formatString: 0
		lineageTag: 88a16f07-5506-4e8d-83fa-d205e25251c4
		summarizeBy: sum
		isNameInferred
		sourceColumn: [GolsPro]

		annotation SummarizationSetBy = Automatic

	column GolsContra
		formatString: 0
		lineageTag: 55609c83-d5da-4af3-9140-1f4f9d5ebf1f
		summarizeBy: sum
		isNameInferred
		sourceColumn: [GolsContra]

		annotation SummarizationSetBy = Automatic

	column Ano
		formatString: 0
		lineageTag: f8194a54-83ee-4ecb-bde2-c98acf17babe
		summarizeBy: none
		isNameInferred
		sourceColumn: full - unpivot[Ano]

		annotation SummarizationSetBy = Automatic

	column Série
		lineageTag: 7f0a72aa-cb3b-469c-bd5b-5d494d5c1280
		summarizeBy: none
		isNameInferred
		sourceColumn: full - unpivot[Série]

		annotation SummarizationSetBy = Automatic

	column StatusTime = ```
			
			VAR Ranking = [Ranking_times]
			VAR TotalTimesAno = 
			    CALCULATE(
			        COUNTROWS(fct_classificacao),
			        ALLEXCEPT(fct_classificacao, fct_classificacao[Ano])
			    )
			RETURN
			IF(Ranking = 1, "Vencedor", 
			    IF(Ranking > TotalTimesAno - 4, "Rebaixado", BLANK()))
			
			```
		lineageTag: d7d8dd9f-d0ec-4b39-a135-88c1b6f7f1f5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition fct_classificacao = calculated
		mode: import
		source = ```
				
				SUMMARIZE(
				    FILTER(
				        'full - unpivot',
				        VAR AnoData = YEAR('full - unpivot'[Data])
				        VAR MesData = MONTH('full - unpivot'[Data])
				        RETURN
				            IF(
				                AnoData = 2021 && MesData < 3, 
				                2020, 
				                AnoData
				            ) = 'full - unpivot'[Ano] 
				    ),
				    'full - unpivot'[time],
				    'full - unpivot'[Ano],
				    'full - unpivot'[Série],
				    "TotalJogos", DISTINCTCOUNT('full - unpivot'[ID]),
				    "TotalPontos", SUM('full - unpivot'[Pontos]),
				    "TotalVitorias", CALCULATE(DISTINCTCOUNT('full - unpivot'[ID]), 'full - unpivot'[R] = "V"),
				    "TotalDerrotas", CALCULATE(DISTINCTCOUNT('full - unpivot'[ID]), 'full - unpivot'[R] = "D"),
				    "TotalEmpates", CALCULATE(DISTINCTCOUNT('full - unpivot'[ID]), 'full - unpivot'[R] = "E"),
				    "GolsPro", SUM('full - unpivot'[gols_pro]),
				    "GolsContra", SUM('full - unpivot'[gols_contra]),
				    "SaldoGols", SUM('full - unpivot'[Saldo Gols])
				)
				
				```

	annotation PBI_Id = 69c9dc6adcd04c4d9c2c6f35b9d53761

